// Black-box stub for rope_apply tile macro (hierarchical PnR).
// Pure stdcell datapath + 1024-bit cos/sin pass-through registers.
(* blackbox *)
module rope_apply (
  input  wire          clk,
  input  wire          rst,
  input  wire          forward_cos_valid_in,
  input  wire [1023:0] forward_cos_v_in,
  input  wire          forward_cos_rden_in,
  input  wire          forward_sin_valid_in,
  input  wire [1023:0] forward_sin_v_in,
  input  wire          forward_sin_rden_in,
  input  wire          read_cos_forwarded_valid_in,
  input  wire          read_cos_forwarded_rden_in,
  input  wire          read_sin_forwarded_valid_in,
  input  wire          read_sin_forwarded_rden_in,
  input  wire          rotate_even_valid_in,
  input  wire [15:0]   rotate_even_x_even_in,
  input  wire [15:0]   rotate_even_x_odd_in,
  input  wire [15:0]   rotate_even_cos_val_in,
  input  wire [15:0]   rotate_even_sin_val_in,
  input  wire          rotate_even_rden_in,
  input  wire          rotate_odd_valid_in,
  input  wire [15:0]   rotate_odd_x_even_in,
  input  wire [15:0]   rotate_odd_x_odd_in,
  input  wire [15:0]   rotate_odd_cos_val_in,
  input  wire [15:0]   rotate_odd_sin_val_in,
  input  wire          rotate_odd_rden_in,
  input  wire [2:0]    stall_rate_in,
  input  wire          stall_rate_valid_in,
  output wire          rst_and_startup_done_out,
  output wire          forward_cos_rdy_out,
  output wire          forward_cos_empty_out,
  output wire          forward_sin_rdy_out,
  output wire          forward_sin_empty_out,
  output wire          read_cos_forwarded_rdy_out,
  output wire          read_cos_forwarded_empty_out,
  output wire [1023:0] read_cos_forwarded_result_out,
  output wire          read_sin_forwarded_rdy_out,
  output wire          read_sin_forwarded_empty_out,
  output wire [1023:0] read_sin_forwarded_result_out,
  output wire          rotate_even_rdy_out,
  output wire          rotate_even_empty_out,
  output wire [15:0]   rotate_even_result_out,
  output wire          rotate_odd_rdy_out,
  output wire          rotate_odd_empty_out,
  output wire [15:0]   rotate_odd_result_out,
  output wire          stall_rate_supported_out
);
endmodule
