// =============================================================================
// transformer_layer_wrapper.sv
//
// Structural wrapper composing all sub-modules for one transformer layer.
// Auto-generated — do not edit by hand.
// =============================================================================

module transformer_layer_wrapper (
  input  wire           clk,
  input  wire           rst,
  input  wire [   2:0] stall_rate_in,
  input  wire           stall_rate_valid_in,
  input  wire           mac_q_mac_step_valid_in,
  input  wire [   1:0] mac_q_mac_step_pe_id_in,
  input  wire [   3:0] mac_q_mac_step_magnitude_in,
  input  wire           mac_q_mac_step_sign_bit_in,
  input  wire [   7:0] mac_q_mac_step_activation_in,
  input  wire           mac_q_mac_step_rden_in,
  input  wire           mac_q_read_accum_valid_in,
  input  wire [   1:0] mac_q_read_accum_pe_id_in,
  input  wire           mac_q_read_accum_rden_in,
  input  wire           mac_q_read_rom_block_valid_in,
  input  wire [  15:0] mac_q_read_rom_block_block_addr_in,
  input  wire           mac_q_read_rom_block_rden_in,
  input  wire           mac_q_write_rom_block_valid_in,
  input  wire [  15:0] mac_q_write_rom_block_block_addr_in,
  input  wire [ 879:0] mac_q_write_rom_block_value_in,
  input  wire           mac_q_write_rom_block_rden_in,
  input  wire           mac_q_read_grid_valid_in,
  input  wire [   8:0] mac_q_read_grid_index_in,
  input  wire           mac_q_read_grid_rden_in,
  input  wire           mac_q_write_grid_valid_in,
  input  wire [   8:0] mac_q_write_grid_index_in,
  input  wire [  31:0] mac_q_write_grid_value_in,
  input  wire           mac_q_write_grid_rden_in,
  input  wire           mac_q_set_fp32_accum_valid_in,
  input  wire [   1:0] mac_q_set_fp32_accum_pe_id_in,
  input  wire [  31:0] mac_q_set_fp32_accum_value_in,
  input  wire           mac_q_set_fp32_accum_rden_in,
  input  wire           mac_q_read_fp32_accum_valid_in,
  input  wire [   1:0] mac_q_read_fp32_accum_pe_id_in,
  input  wire           mac_q_read_fp32_accum_rden_in,
  input  wire           mac_q_clear_pe_valid_in,
  input  wire [   1:0] mac_q_clear_pe_pe_id_in,
  input  wire           mac_q_clear_pe_rden_in,
  input  wire           mac_q_clear_fp32_valid_in,
  input  wire [   1:0] mac_q_clear_fp32_pe_id_in,
  input  wire           mac_q_clear_fp32_rden_in,
  input  wire           mac_q_clear_all_valid_in,
  input  wire           mac_q_clear_all_rden_in,
  output wire           mac_q_rst_and_startup_done_out,
  output wire           mac_q_mac_step_rdy_out,
  output wire           mac_q_mac_step_empty_out,
  output wire [  23:0] mac_q_mac_step_result_out,
  output wire           mac_q_read_accum_rdy_out,
  output wire           mac_q_read_accum_empty_out,
  output wire [  23:0] mac_q_read_accum_result_out,
  output wire           mac_q_read_rom_block_rdy_out,
  output wire           mac_q_read_rom_block_empty_out,
  output wire [ 879:0] mac_q_read_rom_block_result_out,
  output wire           mac_q_write_rom_block_rdy_out,
  output wire           mac_q_write_rom_block_empty_out,
  output wire           mac_q_read_grid_rdy_out,
  output wire           mac_q_read_grid_empty_out,
  output wire [  31:0] mac_q_read_grid_result_out,
  output wire           mac_q_write_grid_rdy_out,
  output wire           mac_q_write_grid_empty_out,
  output wire           mac_q_set_fp32_accum_rdy_out,
  output wire           mac_q_set_fp32_accum_empty_out,
  output wire           mac_q_read_fp32_accum_rdy_out,
  output wire           mac_q_read_fp32_accum_empty_out,
  output wire [  31:0] mac_q_read_fp32_accum_result_out,
  output wire           mac_q_clear_pe_rdy_out,
  output wire           mac_q_clear_pe_empty_out,
  output wire           mac_q_clear_fp32_rdy_out,
  output wire           mac_q_clear_fp32_empty_out,
  output wire           mac_q_clear_all_rdy_out,
  output wire           mac_q_clear_all_empty_out,
  input  wire           mac_k_mac_step_valid_in,
  input  wire [   1:0] mac_k_mac_step_pe_id_in,
  input  wire [   3:0] mac_k_mac_step_magnitude_in,
  input  wire           mac_k_mac_step_sign_bit_in,
  input  wire [   7:0] mac_k_mac_step_activation_in,
  input  wire           mac_k_mac_step_rden_in,
  input  wire           mac_k_read_accum_valid_in,
  input  wire [   1:0] mac_k_read_accum_pe_id_in,
  input  wire           mac_k_read_accum_rden_in,
  input  wire           mac_k_read_rom_block_valid_in,
  input  wire [  15:0] mac_k_read_rom_block_block_addr_in,
  input  wire           mac_k_read_rom_block_rden_in,
  input  wire           mac_k_write_rom_block_valid_in,
  input  wire [  15:0] mac_k_write_rom_block_block_addr_in,
  input  wire [ 879:0] mac_k_write_rom_block_value_in,
  input  wire           mac_k_write_rom_block_rden_in,
  input  wire           mac_k_read_grid_valid_in,
  input  wire [   8:0] mac_k_read_grid_index_in,
  input  wire           mac_k_read_grid_rden_in,
  input  wire           mac_k_write_grid_valid_in,
  input  wire [   8:0] mac_k_write_grid_index_in,
  input  wire [  31:0] mac_k_write_grid_value_in,
  input  wire           mac_k_write_grid_rden_in,
  input  wire           mac_k_set_fp32_accum_valid_in,
  input  wire [   1:0] mac_k_set_fp32_accum_pe_id_in,
  input  wire [  31:0] mac_k_set_fp32_accum_value_in,
  input  wire           mac_k_set_fp32_accum_rden_in,
  input  wire           mac_k_read_fp32_accum_valid_in,
  input  wire [   1:0] mac_k_read_fp32_accum_pe_id_in,
  input  wire           mac_k_read_fp32_accum_rden_in,
  input  wire           mac_k_clear_pe_valid_in,
  input  wire [   1:0] mac_k_clear_pe_pe_id_in,
  input  wire           mac_k_clear_pe_rden_in,
  input  wire           mac_k_clear_fp32_valid_in,
  input  wire [   1:0] mac_k_clear_fp32_pe_id_in,
  input  wire           mac_k_clear_fp32_rden_in,
  input  wire           mac_k_clear_all_valid_in,
  input  wire           mac_k_clear_all_rden_in,
  output wire           mac_k_rst_and_startup_done_out,
  output wire           mac_k_mac_step_rdy_out,
  output wire           mac_k_mac_step_empty_out,
  output wire [  23:0] mac_k_mac_step_result_out,
  output wire           mac_k_read_accum_rdy_out,
  output wire           mac_k_read_accum_empty_out,
  output wire [  23:0] mac_k_read_accum_result_out,
  output wire           mac_k_read_rom_block_rdy_out,
  output wire           mac_k_read_rom_block_empty_out,
  output wire [ 879:0] mac_k_read_rom_block_result_out,
  output wire           mac_k_write_rom_block_rdy_out,
  output wire           mac_k_write_rom_block_empty_out,
  output wire           mac_k_read_grid_rdy_out,
  output wire           mac_k_read_grid_empty_out,
  output wire [  31:0] mac_k_read_grid_result_out,
  output wire           mac_k_write_grid_rdy_out,
  output wire           mac_k_write_grid_empty_out,
  output wire           mac_k_set_fp32_accum_rdy_out,
  output wire           mac_k_set_fp32_accum_empty_out,
  output wire           mac_k_read_fp32_accum_rdy_out,
  output wire           mac_k_read_fp32_accum_empty_out,
  output wire [  31:0] mac_k_read_fp32_accum_result_out,
  output wire           mac_k_clear_pe_rdy_out,
  output wire           mac_k_clear_pe_empty_out,
  output wire           mac_k_clear_fp32_rdy_out,
  output wire           mac_k_clear_fp32_empty_out,
  output wire           mac_k_clear_all_rdy_out,
  output wire           mac_k_clear_all_empty_out,
  input  wire           mac_v_mac_step_valid_in,
  input  wire [   1:0] mac_v_mac_step_pe_id_in,
  input  wire [   3:0] mac_v_mac_step_magnitude_in,
  input  wire           mac_v_mac_step_sign_bit_in,
  input  wire [   7:0] mac_v_mac_step_activation_in,
  input  wire           mac_v_mac_step_rden_in,
  input  wire           mac_v_read_accum_valid_in,
  input  wire [   1:0] mac_v_read_accum_pe_id_in,
  input  wire           mac_v_read_accum_rden_in,
  input  wire           mac_v_read_rom_block_valid_in,
  input  wire [  15:0] mac_v_read_rom_block_block_addr_in,
  input  wire           mac_v_read_rom_block_rden_in,
  input  wire           mac_v_write_rom_block_valid_in,
  input  wire [  15:0] mac_v_write_rom_block_block_addr_in,
  input  wire [ 879:0] mac_v_write_rom_block_value_in,
  input  wire           mac_v_write_rom_block_rden_in,
  input  wire           mac_v_read_grid_valid_in,
  input  wire [   8:0] mac_v_read_grid_index_in,
  input  wire           mac_v_read_grid_rden_in,
  input  wire           mac_v_write_grid_valid_in,
  input  wire [   8:0] mac_v_write_grid_index_in,
  input  wire [  31:0] mac_v_write_grid_value_in,
  input  wire           mac_v_write_grid_rden_in,
  input  wire           mac_v_set_fp32_accum_valid_in,
  input  wire [   1:0] mac_v_set_fp32_accum_pe_id_in,
  input  wire [  31:0] mac_v_set_fp32_accum_value_in,
  input  wire           mac_v_set_fp32_accum_rden_in,
  input  wire           mac_v_read_fp32_accum_valid_in,
  input  wire [   1:0] mac_v_read_fp32_accum_pe_id_in,
  input  wire           mac_v_read_fp32_accum_rden_in,
  input  wire           mac_v_clear_pe_valid_in,
  input  wire [   1:0] mac_v_clear_pe_pe_id_in,
  input  wire           mac_v_clear_pe_rden_in,
  input  wire           mac_v_clear_fp32_valid_in,
  input  wire [   1:0] mac_v_clear_fp32_pe_id_in,
  input  wire           mac_v_clear_fp32_rden_in,
  input  wire           mac_v_clear_all_valid_in,
  input  wire           mac_v_clear_all_rden_in,
  output wire           mac_v_rst_and_startup_done_out,
  output wire           mac_v_mac_step_rdy_out,
  output wire           mac_v_mac_step_empty_out,
  output wire [  23:0] mac_v_mac_step_result_out,
  output wire           mac_v_read_accum_rdy_out,
  output wire           mac_v_read_accum_empty_out,
  output wire [  23:0] mac_v_read_accum_result_out,
  output wire           mac_v_read_rom_block_rdy_out,
  output wire           mac_v_read_rom_block_empty_out,
  output wire [ 879:0] mac_v_read_rom_block_result_out,
  output wire           mac_v_write_rom_block_rdy_out,
  output wire           mac_v_write_rom_block_empty_out,
  output wire           mac_v_read_grid_rdy_out,
  output wire           mac_v_read_grid_empty_out,
  output wire [  31:0] mac_v_read_grid_result_out,
  output wire           mac_v_write_grid_rdy_out,
  output wire           mac_v_write_grid_empty_out,
  output wire           mac_v_set_fp32_accum_rdy_out,
  output wire           mac_v_set_fp32_accum_empty_out,
  output wire           mac_v_read_fp32_accum_rdy_out,
  output wire           mac_v_read_fp32_accum_empty_out,
  output wire [  31:0] mac_v_read_fp32_accum_result_out,
  output wire           mac_v_clear_pe_rdy_out,
  output wire           mac_v_clear_pe_empty_out,
  output wire           mac_v_clear_fp32_rdy_out,
  output wire           mac_v_clear_fp32_empty_out,
  output wire           mac_v_clear_all_rdy_out,
  output wire           mac_v_clear_all_empty_out,
  input  wire           mac_o_mac_step_valid_in,
  input  wire [   1:0] mac_o_mac_step_pe_id_in,
  input  wire [   3:0] mac_o_mac_step_magnitude_in,
  input  wire           mac_o_mac_step_sign_bit_in,
  input  wire [   7:0] mac_o_mac_step_activation_in,
  input  wire           mac_o_mac_step_rden_in,
  input  wire           mac_o_read_accum_valid_in,
  input  wire [   1:0] mac_o_read_accum_pe_id_in,
  input  wire           mac_o_read_accum_rden_in,
  input  wire           mac_o_read_rom_block_valid_in,
  input  wire [  15:0] mac_o_read_rom_block_block_addr_in,
  input  wire           mac_o_read_rom_block_rden_in,
  input  wire           mac_o_write_rom_block_valid_in,
  input  wire [  15:0] mac_o_write_rom_block_block_addr_in,
  input  wire [ 879:0] mac_o_write_rom_block_value_in,
  input  wire           mac_o_write_rom_block_rden_in,
  input  wire           mac_o_read_grid_valid_in,
  input  wire [   8:0] mac_o_read_grid_index_in,
  input  wire           mac_o_read_grid_rden_in,
  input  wire           mac_o_write_grid_valid_in,
  input  wire [   8:0] mac_o_write_grid_index_in,
  input  wire [  31:0] mac_o_write_grid_value_in,
  input  wire           mac_o_write_grid_rden_in,
  input  wire           mac_o_set_fp32_accum_valid_in,
  input  wire [   1:0] mac_o_set_fp32_accum_pe_id_in,
  input  wire [  31:0] mac_o_set_fp32_accum_value_in,
  input  wire           mac_o_set_fp32_accum_rden_in,
  input  wire           mac_o_read_fp32_accum_valid_in,
  input  wire [   1:0] mac_o_read_fp32_accum_pe_id_in,
  input  wire           mac_o_read_fp32_accum_rden_in,
  input  wire           mac_o_clear_pe_valid_in,
  input  wire [   1:0] mac_o_clear_pe_pe_id_in,
  input  wire           mac_o_clear_pe_rden_in,
  input  wire           mac_o_clear_fp32_valid_in,
  input  wire [   1:0] mac_o_clear_fp32_pe_id_in,
  input  wire           mac_o_clear_fp32_rden_in,
  input  wire           mac_o_clear_all_valid_in,
  input  wire           mac_o_clear_all_rden_in,
  output wire           mac_o_rst_and_startup_done_out,
  output wire           mac_o_mac_step_rdy_out,
  output wire           mac_o_mac_step_empty_out,
  output wire [  23:0] mac_o_mac_step_result_out,
  output wire           mac_o_read_accum_rdy_out,
  output wire           mac_o_read_accum_empty_out,
  output wire [  23:0] mac_o_read_accum_result_out,
  output wire           mac_o_read_rom_block_rdy_out,
  output wire           mac_o_read_rom_block_empty_out,
  output wire [ 879:0] mac_o_read_rom_block_result_out,
  output wire           mac_o_write_rom_block_rdy_out,
  output wire           mac_o_write_rom_block_empty_out,
  output wire           mac_o_read_grid_rdy_out,
  output wire           mac_o_read_grid_empty_out,
  output wire [  31:0] mac_o_read_grid_result_out,
  output wire           mac_o_write_grid_rdy_out,
  output wire           mac_o_write_grid_empty_out,
  output wire           mac_o_set_fp32_accum_rdy_out,
  output wire           mac_o_set_fp32_accum_empty_out,
  output wire           mac_o_read_fp32_accum_rdy_out,
  output wire           mac_o_read_fp32_accum_empty_out,
  output wire [  31:0] mac_o_read_fp32_accum_result_out,
  output wire           mac_o_clear_pe_rdy_out,
  output wire           mac_o_clear_pe_empty_out,
  output wire           mac_o_clear_fp32_rdy_out,
  output wire           mac_o_clear_fp32_empty_out,
  output wire           mac_o_clear_all_rdy_out,
  output wire           mac_o_clear_all_empty_out,
  input  wire           mac_gate_mac_step_valid_in,
  input  wire [   1:0] mac_gate_mac_step_pe_id_in,
  input  wire [   3:0] mac_gate_mac_step_magnitude_in,
  input  wire           mac_gate_mac_step_sign_bit_in,
  input  wire [   7:0] mac_gate_mac_step_activation_in,
  input  wire           mac_gate_mac_step_rden_in,
  input  wire           mac_gate_read_accum_valid_in,
  input  wire [   1:0] mac_gate_read_accum_pe_id_in,
  input  wire           mac_gate_read_accum_rden_in,
  input  wire           mac_gate_read_rom_block_valid_in,
  input  wire [  15:0] mac_gate_read_rom_block_block_addr_in,
  input  wire           mac_gate_read_rom_block_rden_in,
  input  wire           mac_gate_write_rom_block_valid_in,
  input  wire [  15:0] mac_gate_write_rom_block_block_addr_in,
  input  wire [ 879:0] mac_gate_write_rom_block_value_in,
  input  wire           mac_gate_write_rom_block_rden_in,
  input  wire           mac_gate_read_grid_valid_in,
  input  wire [   8:0] mac_gate_read_grid_index_in,
  input  wire           mac_gate_read_grid_rden_in,
  input  wire           mac_gate_write_grid_valid_in,
  input  wire [   8:0] mac_gate_write_grid_index_in,
  input  wire [  31:0] mac_gate_write_grid_value_in,
  input  wire           mac_gate_write_grid_rden_in,
  input  wire           mac_gate_set_fp32_accum_valid_in,
  input  wire [   1:0] mac_gate_set_fp32_accum_pe_id_in,
  input  wire [  31:0] mac_gate_set_fp32_accum_value_in,
  input  wire           mac_gate_set_fp32_accum_rden_in,
  input  wire           mac_gate_read_fp32_accum_valid_in,
  input  wire [   1:0] mac_gate_read_fp32_accum_pe_id_in,
  input  wire           mac_gate_read_fp32_accum_rden_in,
  input  wire           mac_gate_clear_pe_valid_in,
  input  wire [   1:0] mac_gate_clear_pe_pe_id_in,
  input  wire           mac_gate_clear_pe_rden_in,
  input  wire           mac_gate_clear_fp32_valid_in,
  input  wire [   1:0] mac_gate_clear_fp32_pe_id_in,
  input  wire           mac_gate_clear_fp32_rden_in,
  input  wire           mac_gate_clear_all_valid_in,
  input  wire           mac_gate_clear_all_rden_in,
  output wire           mac_gate_rst_and_startup_done_out,
  output wire           mac_gate_mac_step_rdy_out,
  output wire           mac_gate_mac_step_empty_out,
  output wire [  23:0] mac_gate_mac_step_result_out,
  output wire           mac_gate_read_accum_rdy_out,
  output wire           mac_gate_read_accum_empty_out,
  output wire [  23:0] mac_gate_read_accum_result_out,
  output wire           mac_gate_read_rom_block_rdy_out,
  output wire           mac_gate_read_rom_block_empty_out,
  output wire [ 879:0] mac_gate_read_rom_block_result_out,
  output wire           mac_gate_write_rom_block_rdy_out,
  output wire           mac_gate_write_rom_block_empty_out,
  output wire           mac_gate_read_grid_rdy_out,
  output wire           mac_gate_read_grid_empty_out,
  output wire [  31:0] mac_gate_read_grid_result_out,
  output wire           mac_gate_write_grid_rdy_out,
  output wire           mac_gate_write_grid_empty_out,
  output wire           mac_gate_set_fp32_accum_rdy_out,
  output wire           mac_gate_set_fp32_accum_empty_out,
  output wire           mac_gate_read_fp32_accum_rdy_out,
  output wire           mac_gate_read_fp32_accum_empty_out,
  output wire [  31:0] mac_gate_read_fp32_accum_result_out,
  output wire           mac_gate_clear_pe_rdy_out,
  output wire           mac_gate_clear_pe_empty_out,
  output wire           mac_gate_clear_fp32_rdy_out,
  output wire           mac_gate_clear_fp32_empty_out,
  output wire           mac_gate_clear_all_rdy_out,
  output wire           mac_gate_clear_all_empty_out,
  input  wire           mac_up_mac_step_valid_in,
  input  wire [   1:0] mac_up_mac_step_pe_id_in,
  input  wire [   3:0] mac_up_mac_step_magnitude_in,
  input  wire           mac_up_mac_step_sign_bit_in,
  input  wire [   7:0] mac_up_mac_step_activation_in,
  input  wire           mac_up_mac_step_rden_in,
  input  wire           mac_up_read_accum_valid_in,
  input  wire [   1:0] mac_up_read_accum_pe_id_in,
  input  wire           mac_up_read_accum_rden_in,
  input  wire           mac_up_read_rom_block_valid_in,
  input  wire [  15:0] mac_up_read_rom_block_block_addr_in,
  input  wire           mac_up_read_rom_block_rden_in,
  input  wire           mac_up_write_rom_block_valid_in,
  input  wire [  15:0] mac_up_write_rom_block_block_addr_in,
  input  wire [ 879:0] mac_up_write_rom_block_value_in,
  input  wire           mac_up_write_rom_block_rden_in,
  input  wire           mac_up_read_grid_valid_in,
  input  wire [   8:0] mac_up_read_grid_index_in,
  input  wire           mac_up_read_grid_rden_in,
  input  wire           mac_up_write_grid_valid_in,
  input  wire [   8:0] mac_up_write_grid_index_in,
  input  wire [  31:0] mac_up_write_grid_value_in,
  input  wire           mac_up_write_grid_rden_in,
  input  wire           mac_up_set_fp32_accum_valid_in,
  input  wire [   1:0] mac_up_set_fp32_accum_pe_id_in,
  input  wire [  31:0] mac_up_set_fp32_accum_value_in,
  input  wire           mac_up_set_fp32_accum_rden_in,
  input  wire           mac_up_read_fp32_accum_valid_in,
  input  wire [   1:0] mac_up_read_fp32_accum_pe_id_in,
  input  wire           mac_up_read_fp32_accum_rden_in,
  input  wire           mac_up_clear_pe_valid_in,
  input  wire [   1:0] mac_up_clear_pe_pe_id_in,
  input  wire           mac_up_clear_pe_rden_in,
  input  wire           mac_up_clear_fp32_valid_in,
  input  wire [   1:0] mac_up_clear_fp32_pe_id_in,
  input  wire           mac_up_clear_fp32_rden_in,
  input  wire           mac_up_clear_all_valid_in,
  input  wire           mac_up_clear_all_rden_in,
  output wire           mac_up_rst_and_startup_done_out,
  output wire           mac_up_mac_step_rdy_out,
  output wire           mac_up_mac_step_empty_out,
  output wire [  23:0] mac_up_mac_step_result_out,
  output wire           mac_up_read_accum_rdy_out,
  output wire           mac_up_read_accum_empty_out,
  output wire [  23:0] mac_up_read_accum_result_out,
  output wire           mac_up_read_rom_block_rdy_out,
  output wire           mac_up_read_rom_block_empty_out,
  output wire [ 879:0] mac_up_read_rom_block_result_out,
  output wire           mac_up_write_rom_block_rdy_out,
  output wire           mac_up_write_rom_block_empty_out,
  output wire           mac_up_read_grid_rdy_out,
  output wire           mac_up_read_grid_empty_out,
  output wire [  31:0] mac_up_read_grid_result_out,
  output wire           mac_up_write_grid_rdy_out,
  output wire           mac_up_write_grid_empty_out,
  output wire           mac_up_set_fp32_accum_rdy_out,
  output wire           mac_up_set_fp32_accum_empty_out,
  output wire           mac_up_read_fp32_accum_rdy_out,
  output wire           mac_up_read_fp32_accum_empty_out,
  output wire [  31:0] mac_up_read_fp32_accum_result_out,
  output wire           mac_up_clear_pe_rdy_out,
  output wire           mac_up_clear_pe_empty_out,
  output wire           mac_up_clear_fp32_rdy_out,
  output wire           mac_up_clear_fp32_empty_out,
  output wire           mac_up_clear_all_rdy_out,
  output wire           mac_up_clear_all_empty_out,
  input  wire           mac_down_mac_step_valid_in,
  input  wire [   1:0] mac_down_mac_step_pe_id_in,
  input  wire [   3:0] mac_down_mac_step_magnitude_in,
  input  wire           mac_down_mac_step_sign_bit_in,
  input  wire [   7:0] mac_down_mac_step_activation_in,
  input  wire           mac_down_mac_step_rden_in,
  input  wire           mac_down_read_accum_valid_in,
  input  wire [   1:0] mac_down_read_accum_pe_id_in,
  input  wire           mac_down_read_accum_rden_in,
  input  wire           mac_down_read_rom_block_valid_in,
  input  wire [  15:0] mac_down_read_rom_block_block_addr_in,
  input  wire           mac_down_read_rom_block_rden_in,
  input  wire           mac_down_write_rom_block_valid_in,
  input  wire [  15:0] mac_down_write_rom_block_block_addr_in,
  input  wire [ 879:0] mac_down_write_rom_block_value_in,
  input  wire           mac_down_write_rom_block_rden_in,
  input  wire           mac_down_read_grid_valid_in,
  input  wire [   8:0] mac_down_read_grid_index_in,
  input  wire           mac_down_read_grid_rden_in,
  input  wire           mac_down_write_grid_valid_in,
  input  wire [   8:0] mac_down_write_grid_index_in,
  input  wire [  31:0] mac_down_write_grid_value_in,
  input  wire           mac_down_write_grid_rden_in,
  input  wire           mac_down_set_fp32_accum_valid_in,
  input  wire [   1:0] mac_down_set_fp32_accum_pe_id_in,
  input  wire [  31:0] mac_down_set_fp32_accum_value_in,
  input  wire           mac_down_set_fp32_accum_rden_in,
  input  wire           mac_down_read_fp32_accum_valid_in,
  input  wire [   1:0] mac_down_read_fp32_accum_pe_id_in,
  input  wire           mac_down_read_fp32_accum_rden_in,
  input  wire           mac_down_clear_pe_valid_in,
  input  wire [   1:0] mac_down_clear_pe_pe_id_in,
  input  wire           mac_down_clear_pe_rden_in,
  input  wire           mac_down_clear_fp32_valid_in,
  input  wire [   1:0] mac_down_clear_fp32_pe_id_in,
  input  wire           mac_down_clear_fp32_rden_in,
  input  wire           mac_down_clear_all_valid_in,
  input  wire           mac_down_clear_all_rden_in,
  output wire           mac_down_rst_and_startup_done_out,
  output wire           mac_down_mac_step_rdy_out,
  output wire           mac_down_mac_step_empty_out,
  output wire [  23:0] mac_down_mac_step_result_out,
  output wire           mac_down_read_accum_rdy_out,
  output wire           mac_down_read_accum_empty_out,
  output wire [  23:0] mac_down_read_accum_result_out,
  output wire           mac_down_read_rom_block_rdy_out,
  output wire           mac_down_read_rom_block_empty_out,
  output wire [ 879:0] mac_down_read_rom_block_result_out,
  output wire           mac_down_write_rom_block_rdy_out,
  output wire           mac_down_write_rom_block_empty_out,
  output wire           mac_down_read_grid_rdy_out,
  output wire           mac_down_read_grid_empty_out,
  output wire [  31:0] mac_down_read_grid_result_out,
  output wire           mac_down_write_grid_rdy_out,
  output wire           mac_down_write_grid_empty_out,
  output wire           mac_down_set_fp32_accum_rdy_out,
  output wire           mac_down_set_fp32_accum_empty_out,
  output wire           mac_down_read_fp32_accum_rdy_out,
  output wire           mac_down_read_fp32_accum_empty_out,
  output wire [  31:0] mac_down_read_fp32_accum_result_out,
  output wire           mac_down_clear_pe_rdy_out,
  output wire           mac_down_clear_pe_empty_out,
  output wire           mac_down_clear_fp32_rdy_out,
  output wire           mac_down_clear_fp32_empty_out,
  output wire           mac_down_clear_all_rdy_out,
  output wire           mac_down_clear_all_empty_out,
  input  wire           vpu_rmsnorm_accumulate_valid_in,
  input  wire [  15:0] vpu_rmsnorm_accumulate_x_bf16_in,
  input  wire           vpu_rmsnorm_accumulate_rden_in,
  input  wire           vpu_rmsnorm_get_sum_valid_in,
  input  wire           vpu_rmsnorm_get_sum_rden_in,
  input  wire           vpu_rmsnorm_reset_valid_in,
  input  wire           vpu_rmsnorm_reset_rden_in,
  input  wire           vpu_set_gamma_pre_attn_valid_in,
  input  wire [  15:0] vpu_set_gamma_pre_attn_index_in,
  input  wire [  15:0] vpu_set_gamma_pre_attn_value_in,
  input  wire           vpu_set_gamma_pre_attn_rden_in,
  input  wire           vpu_get_gamma_pre_attn_valid_in,
  input  wire [  15:0] vpu_get_gamma_pre_attn_index_in,
  input  wire           vpu_get_gamma_pre_attn_rden_in,
  input  wire           vpu_set_gamma_pre_mlp_valid_in,
  input  wire [  15:0] vpu_set_gamma_pre_mlp_index_in,
  input  wire [  15:0] vpu_set_gamma_pre_mlp_value_in,
  input  wire           vpu_set_gamma_pre_mlp_rden_in,
  input  wire           vpu_get_gamma_pre_mlp_valid_in,
  input  wire [  15:0] vpu_get_gamma_pre_mlp_index_in,
  input  wire           vpu_get_gamma_pre_mlp_rden_in,
  input  wire           vpu_set_rsqrt_lut_valid_in,
  input  wire [   7:0] vpu_set_rsqrt_lut_index_in,
  input  wire [  15:0] vpu_set_rsqrt_lut_value_in,
  input  wire           vpu_set_rsqrt_lut_rden_in,
  input  wire           vpu_lookup_rsqrt_valid_in,
  input  wire [   7:0] vpu_lookup_rsqrt_index_in,
  input  wire           vpu_lookup_rsqrt_rden_in,
  input  wire           vpu_rope_read_cos_row_valid_in,
  input  wire [  11:0] vpu_rope_read_cos_row_position_in,
  input  wire           vpu_rope_read_cos_row_rden_in,
  input  wire           vpu_rope_read_sin_row_valid_in,
  input  wire [  11:0] vpu_rope_read_sin_row_position_in,
  input  wire           vpu_rope_read_sin_row_rden_in,
  input  wire           vpu_rope_write_cos_row_valid_in,
  input  wire [  11:0] vpu_rope_write_cos_row_position_in,
  input  wire [1023:0] vpu_rope_write_cos_row_value_in,
  input  wire           vpu_rope_write_cos_row_rden_in,
  input  wire           vpu_rope_write_sin_row_valid_in,
  input  wire [  11:0] vpu_rope_write_sin_row_position_in,
  input  wire [1023:0] vpu_rope_write_sin_row_value_in,
  input  wire           vpu_rope_write_sin_row_rden_in,
  input  wire           vpu_set_sigmoid_lut_valid_in,
  input  wire [   7:0] vpu_set_sigmoid_lut_index_in,
  input  wire [  15:0] vpu_set_sigmoid_lut_value_in,
  input  wire           vpu_set_sigmoid_lut_rden_in,
  input  wire           vpu_swiglu_compute_valid_in,
  input  wire [  15:0] vpu_swiglu_compute_gate_bf16_in,
  input  wire [  15:0] vpu_swiglu_compute_up_bf16_in,
  input  wire           vpu_swiglu_compute_rden_in,
  input  wire           vpu_dequantize_valid_in,
  input  wire [  23:0] vpu_dequantize_accum_in,
  input  wire [  15:0] vpu_dequantize_super_scale_bf16_in,
  input  wire [   3:0] vpu_dequantize_sub_scale_in,
  input  wire           vpu_dequantize_rden_in,
  input  wire           vpu_residual_add_valid_in,
  input  wire [  15:0] vpu_residual_add_a_bf16_in,
  input  wire [  15:0] vpu_residual_add_b_bf16_in,
  input  wire           vpu_residual_add_rden_in,
  output wire           vpu_rst_and_startup_done_out,
  output wire           vpu_rmsnorm_accumulate_rdy_out,
  output wire           vpu_rmsnorm_accumulate_empty_out,
  output wire           vpu_rmsnorm_get_sum_rdy_out,
  output wire           vpu_rmsnorm_get_sum_empty_out,
  output wire [  31:0] vpu_rmsnorm_get_sum_result_out,
  output wire           vpu_rmsnorm_reset_rdy_out,
  output wire           vpu_rmsnorm_reset_empty_out,
  output wire           vpu_set_gamma_pre_attn_rdy_out,
  output wire           vpu_set_gamma_pre_attn_empty_out,
  output wire           vpu_get_gamma_pre_attn_rdy_out,
  output wire           vpu_get_gamma_pre_attn_empty_out,
  output wire [  15:0] vpu_get_gamma_pre_attn_result_out,
  output wire           vpu_set_gamma_pre_mlp_rdy_out,
  output wire           vpu_set_gamma_pre_mlp_empty_out,
  output wire           vpu_get_gamma_pre_mlp_rdy_out,
  output wire           vpu_get_gamma_pre_mlp_empty_out,
  output wire [  15:0] vpu_get_gamma_pre_mlp_result_out,
  output wire           vpu_set_rsqrt_lut_rdy_out,
  output wire           vpu_set_rsqrt_lut_empty_out,
  output wire           vpu_lookup_rsqrt_rdy_out,
  output wire           vpu_lookup_rsqrt_empty_out,
  output wire [  15:0] vpu_lookup_rsqrt_result_out,
  output wire           vpu_rope_read_cos_row_rdy_out,
  output wire           vpu_rope_read_cos_row_empty_out,
  output wire [1023:0] vpu_rope_read_cos_row_result_out,
  output wire           vpu_rope_read_sin_row_rdy_out,
  output wire           vpu_rope_read_sin_row_empty_out,
  output wire [1023:0] vpu_rope_read_sin_row_result_out,
  output wire           vpu_rope_write_cos_row_rdy_out,
  output wire           vpu_rope_write_cos_row_empty_out,
  output wire           vpu_rope_write_sin_row_rdy_out,
  output wire           vpu_rope_write_sin_row_empty_out,
  output wire           vpu_set_sigmoid_lut_rdy_out,
  output wire           vpu_set_sigmoid_lut_empty_out,
  output wire           vpu_swiglu_compute_rdy_out,
  output wire           vpu_swiglu_compute_empty_out,
  output wire [  15:0] vpu_swiglu_compute_result_out,
  output wire           vpu_dequantize_rdy_out,
  output wire           vpu_dequantize_empty_out,
  output wire [  15:0] vpu_dequantize_result_out,
  output wire           vpu_residual_add_rdy_out,
  output wire           vpu_residual_add_empty_out,
  output wire [  15:0] vpu_residual_add_result_out,
  input  wire           kvc_append_k_valid_in,
  input  wire [  11:0] kvc_append_k_token_pos_in,
  input  wire [   3:0] kvc_append_k_head_id_in,
  input  wire [   6:0] kvc_append_k_dim_idx_in,
  input  wire [   7:0] kvc_append_k_value_in,
  input  wire           kvc_append_k_rden_in,
  input  wire           kvc_append_v_valid_in,
  input  wire [  11:0] kvc_append_v_token_pos_in,
  input  wire [   3:0] kvc_append_v_head_id_in,
  input  wire [   6:0] kvc_append_v_dim_idx_in,
  input  wire [   7:0] kvc_append_v_value_in,
  input  wire           kvc_append_v_rden_in,
  input  wire           kvc_read_k_valid_in,
  input  wire [  11:0] kvc_read_k_token_pos_in,
  input  wire [   3:0] kvc_read_k_head_id_in,
  input  wire [   6:0] kvc_read_k_dim_idx_in,
  input  wire           kvc_read_k_rden_in,
  input  wire           kvc_read_v_valid_in,
  input  wire [  11:0] kvc_read_v_token_pos_in,
  input  wire [   3:0] kvc_read_v_head_id_in,
  input  wire [   6:0] kvc_read_v_dim_idx_in,
  input  wire           kvc_read_v_rden_in,
  input  wire           kvc_advance_write_ptr_valid_in,
  input  wire           kvc_advance_write_ptr_rden_in,
  input  wire           kvc_get_seq_len_valid_in,
  input  wire           kvc_get_seq_len_rden_in,
  input  wire           kvc_reset_valid_in,
  input  wire           kvc_reset_rden_in,
  output wire           kvc_rst_and_startup_done_out,
  output wire           kvc_append_k_rdy_out,
  output wire           kvc_append_k_empty_out,
  output wire           kvc_append_v_rdy_out,
  output wire           kvc_append_v_empty_out,
  output wire           kvc_read_k_rdy_out,
  output wire           kvc_read_k_empty_out,
  output wire [   7:0] kvc_read_k_result_out,
  output wire           kvc_read_v_rdy_out,
  output wire           kvc_read_v_empty_out,
  output wire [   7:0] kvc_read_v_result_out,
  output wire           kvc_advance_write_ptr_rdy_out,
  output wire           kvc_advance_write_ptr_empty_out,
  output wire           kvc_get_seq_len_rdy_out,
  output wire           kvc_get_seq_len_empty_out,
  output wire [  11:0] kvc_get_seq_len_result_out,
  output wire           kvc_reset_rdy_out,
  output wire           kvc_reset_empty_out,
  input  wire           attn_dot_product_valid_in,
  input  wire [   7:0] attn_dot_product_q_elem_in,
  input  wire [   7:0] attn_dot_product_k_elem_in,
  input  wire           attn_dot_product_rden_in,
  input  wire           attn_read_score_valid_in,
  input  wire           attn_read_score_rden_in,
  input  wire           attn_clear_score_valid_in,
  input  wire           attn_clear_score_rden_in,
  input  wire           attn_set_max_score_valid_in,
  input  wire [  31:0] attn_set_max_score_score_in,
  input  wire           attn_set_max_score_rden_in,
  input  wire           attn_get_max_score_valid_in,
  input  wire           attn_get_max_score_rden_in,
  output wire           attn_rst_and_startup_done_out,
  output wire           attn_dot_product_rdy_out,
  output wire           attn_dot_product_empty_out,
  output wire [  31:0] attn_dot_product_result_out,
  output wire           attn_read_score_rdy_out,
  output wire           attn_read_score_empty_out,
  output wire [  31:0] attn_read_score_result_out,
  output wire           attn_clear_score_rdy_out,
  output wire           attn_clear_score_empty_out,
  output wire           attn_set_max_score_rdy_out,
  output wire           attn_set_max_score_empty_out,
  output wire           attn_get_max_score_rdy_out,
  output wire           attn_get_max_score_empty_out,
  output wire [  31:0] attn_get_max_score_result_out,
  input  wire           fsm_set_layer_id_valid_in,
  input  wire [  15:0] fsm_set_layer_id_id_in,
  input  wire           fsm_set_layer_id_rden_in,
  input  wire           fsm_get_layer_id_valid_in,
  input  wire           fsm_get_layer_id_rden_in,
  input  wire           fsm_get_state_valid_in,
  input  wire           fsm_get_state_rden_in,
  input  wire           fsm_advance_state_valid_in,
  input  wire           fsm_advance_state_rden_in,
  input  wire           fsm_reset_state_valid_in,
  input  wire           fsm_reset_state_rden_in,
  input  wire           fsm_is_done_valid_in,
  input  wire           fsm_is_done_rden_in,
  input  wire           fsm_get_position_valid_in,
  input  wire           fsm_get_position_rden_in,
  input  wire           fsm_advance_position_valid_in,
  input  wire           fsm_advance_position_rden_in,
  input  wire           fsm_reset_valid_in,
  input  wire           fsm_reset_rden_in,
  output wire           fsm_rst_and_startup_done_out,
  output wire           fsm_set_layer_id_rdy_out,
  output wire           fsm_set_layer_id_empty_out,
  output wire           fsm_get_layer_id_rdy_out,
  output wire           fsm_get_layer_id_empty_out,
  output wire [  15:0] fsm_get_layer_id_result_out,
  output wire           fsm_get_state_rdy_out,
  output wire           fsm_get_state_empty_out,
  output wire [   5:0] fsm_get_state_result_out,
  output wire           fsm_advance_state_rdy_out,
  output wire           fsm_advance_state_empty_out,
  output wire           fsm_reset_state_rdy_out,
  output wire           fsm_reset_state_empty_out,
  output wire           fsm_is_done_rdy_out,
  output wire           fsm_is_done_empty_out,
  output wire           fsm_is_done_result_out,
  output wire           fsm_get_position_rdy_out,
  output wire           fsm_get_position_empty_out,
  output wire [  11:0] fsm_get_position_result_out,
  output wire           fsm_advance_position_rdy_out,
  output wire           fsm_advance_position_empty_out,
  output wire           fsm_reset_rdy_out,
  output wire           fsm_reset_empty_out
);

  mac_array u_mac_q (
    .clk(clk),
    .rst(rst),
    .mac_step_valid_in(mac_q_mac_step_valid_in),
    .mac_step_pe_id_in(mac_q_mac_step_pe_id_in),
    .mac_step_magnitude_in(mac_q_mac_step_magnitude_in),
    .mac_step_sign_bit_in(mac_q_mac_step_sign_bit_in),
    .mac_step_activation_in(mac_q_mac_step_activation_in),
    .mac_step_rden_in(mac_q_mac_step_rden_in),
    .read_accum_valid_in(mac_q_read_accum_valid_in),
    .read_accum_pe_id_in(mac_q_read_accum_pe_id_in),
    .read_accum_rden_in(mac_q_read_accum_rden_in),
    .read_rom_block_valid_in(mac_q_read_rom_block_valid_in),
    .read_rom_block_block_addr_in(mac_q_read_rom_block_block_addr_in),
    .read_rom_block_rden_in(mac_q_read_rom_block_rden_in),
    .write_rom_block_valid_in(mac_q_write_rom_block_valid_in),
    .write_rom_block_block_addr_in(mac_q_write_rom_block_block_addr_in),
    .write_rom_block_value_in(mac_q_write_rom_block_value_in),
    .write_rom_block_rden_in(mac_q_write_rom_block_rden_in),
    .read_grid_valid_in(mac_q_read_grid_valid_in),
    .read_grid_index_in(mac_q_read_grid_index_in),
    .read_grid_rden_in(mac_q_read_grid_rden_in),
    .write_grid_valid_in(mac_q_write_grid_valid_in),
    .write_grid_index_in(mac_q_write_grid_index_in),
    .write_grid_value_in(mac_q_write_grid_value_in),
    .write_grid_rden_in(mac_q_write_grid_rden_in),
    .set_fp32_accum_valid_in(mac_q_set_fp32_accum_valid_in),
    .set_fp32_accum_pe_id_in(mac_q_set_fp32_accum_pe_id_in),
    .set_fp32_accum_value_in(mac_q_set_fp32_accum_value_in),
    .set_fp32_accum_rden_in(mac_q_set_fp32_accum_rden_in),
    .read_fp32_accum_valid_in(mac_q_read_fp32_accum_valid_in),
    .read_fp32_accum_pe_id_in(mac_q_read_fp32_accum_pe_id_in),
    .read_fp32_accum_rden_in(mac_q_read_fp32_accum_rden_in),
    .clear_pe_valid_in(mac_q_clear_pe_valid_in),
    .clear_pe_pe_id_in(mac_q_clear_pe_pe_id_in),
    .clear_pe_rden_in(mac_q_clear_pe_rden_in),
    .clear_fp32_valid_in(mac_q_clear_fp32_valid_in),
    .clear_fp32_pe_id_in(mac_q_clear_fp32_pe_id_in),
    .clear_fp32_rden_in(mac_q_clear_fp32_rden_in),
    .clear_all_valid_in(mac_q_clear_all_valid_in),
    .clear_all_rden_in(mac_q_clear_all_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(mac_q_rst_and_startup_done_out),
    .mac_step_rdy_out(mac_q_mac_step_rdy_out),
    .mac_step_empty_out(mac_q_mac_step_empty_out),
    .mac_step_result_out(mac_q_mac_step_result_out),
    .read_accum_rdy_out(mac_q_read_accum_rdy_out),
    .read_accum_empty_out(mac_q_read_accum_empty_out),
    .read_accum_result_out(mac_q_read_accum_result_out),
    .read_rom_block_rdy_out(mac_q_read_rom_block_rdy_out),
    .read_rom_block_empty_out(mac_q_read_rom_block_empty_out),
    .read_rom_block_result_out(mac_q_read_rom_block_result_out),
    .write_rom_block_rdy_out(mac_q_write_rom_block_rdy_out),
    .write_rom_block_empty_out(mac_q_write_rom_block_empty_out),
    .read_grid_rdy_out(mac_q_read_grid_rdy_out),
    .read_grid_empty_out(mac_q_read_grid_empty_out),
    .read_grid_result_out(mac_q_read_grid_result_out),
    .write_grid_rdy_out(mac_q_write_grid_rdy_out),
    .write_grid_empty_out(mac_q_write_grid_empty_out),
    .set_fp32_accum_rdy_out(mac_q_set_fp32_accum_rdy_out),
    .set_fp32_accum_empty_out(mac_q_set_fp32_accum_empty_out),
    .read_fp32_accum_rdy_out(mac_q_read_fp32_accum_rdy_out),
    .read_fp32_accum_empty_out(mac_q_read_fp32_accum_empty_out),
    .read_fp32_accum_result_out(mac_q_read_fp32_accum_result_out),
    .clear_pe_rdy_out(mac_q_clear_pe_rdy_out),
    .clear_pe_empty_out(mac_q_clear_pe_empty_out),
    .clear_fp32_rdy_out(mac_q_clear_fp32_rdy_out),
    .clear_fp32_empty_out(mac_q_clear_fp32_empty_out),
    .clear_all_rdy_out(mac_q_clear_all_rdy_out),
    .clear_all_empty_out(mac_q_clear_all_empty_out),
    .stall_rate_supported_out()
  );

  mac_array u_mac_k (
    .clk(clk),
    .rst(rst),
    .mac_step_valid_in(mac_k_mac_step_valid_in),
    .mac_step_pe_id_in(mac_k_mac_step_pe_id_in),
    .mac_step_magnitude_in(mac_k_mac_step_magnitude_in),
    .mac_step_sign_bit_in(mac_k_mac_step_sign_bit_in),
    .mac_step_activation_in(mac_k_mac_step_activation_in),
    .mac_step_rden_in(mac_k_mac_step_rden_in),
    .read_accum_valid_in(mac_k_read_accum_valid_in),
    .read_accum_pe_id_in(mac_k_read_accum_pe_id_in),
    .read_accum_rden_in(mac_k_read_accum_rden_in),
    .read_rom_block_valid_in(mac_k_read_rom_block_valid_in),
    .read_rom_block_block_addr_in(mac_k_read_rom_block_block_addr_in),
    .read_rom_block_rden_in(mac_k_read_rom_block_rden_in),
    .write_rom_block_valid_in(mac_k_write_rom_block_valid_in),
    .write_rom_block_block_addr_in(mac_k_write_rom_block_block_addr_in),
    .write_rom_block_value_in(mac_k_write_rom_block_value_in),
    .write_rom_block_rden_in(mac_k_write_rom_block_rden_in),
    .read_grid_valid_in(mac_k_read_grid_valid_in),
    .read_grid_index_in(mac_k_read_grid_index_in),
    .read_grid_rden_in(mac_k_read_grid_rden_in),
    .write_grid_valid_in(mac_k_write_grid_valid_in),
    .write_grid_index_in(mac_k_write_grid_index_in),
    .write_grid_value_in(mac_k_write_grid_value_in),
    .write_grid_rden_in(mac_k_write_grid_rden_in),
    .set_fp32_accum_valid_in(mac_k_set_fp32_accum_valid_in),
    .set_fp32_accum_pe_id_in(mac_k_set_fp32_accum_pe_id_in),
    .set_fp32_accum_value_in(mac_k_set_fp32_accum_value_in),
    .set_fp32_accum_rden_in(mac_k_set_fp32_accum_rden_in),
    .read_fp32_accum_valid_in(mac_k_read_fp32_accum_valid_in),
    .read_fp32_accum_pe_id_in(mac_k_read_fp32_accum_pe_id_in),
    .read_fp32_accum_rden_in(mac_k_read_fp32_accum_rden_in),
    .clear_pe_valid_in(mac_k_clear_pe_valid_in),
    .clear_pe_pe_id_in(mac_k_clear_pe_pe_id_in),
    .clear_pe_rden_in(mac_k_clear_pe_rden_in),
    .clear_fp32_valid_in(mac_k_clear_fp32_valid_in),
    .clear_fp32_pe_id_in(mac_k_clear_fp32_pe_id_in),
    .clear_fp32_rden_in(mac_k_clear_fp32_rden_in),
    .clear_all_valid_in(mac_k_clear_all_valid_in),
    .clear_all_rden_in(mac_k_clear_all_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(mac_k_rst_and_startup_done_out),
    .mac_step_rdy_out(mac_k_mac_step_rdy_out),
    .mac_step_empty_out(mac_k_mac_step_empty_out),
    .mac_step_result_out(mac_k_mac_step_result_out),
    .read_accum_rdy_out(mac_k_read_accum_rdy_out),
    .read_accum_empty_out(mac_k_read_accum_empty_out),
    .read_accum_result_out(mac_k_read_accum_result_out),
    .read_rom_block_rdy_out(mac_k_read_rom_block_rdy_out),
    .read_rom_block_empty_out(mac_k_read_rom_block_empty_out),
    .read_rom_block_result_out(mac_k_read_rom_block_result_out),
    .write_rom_block_rdy_out(mac_k_write_rom_block_rdy_out),
    .write_rom_block_empty_out(mac_k_write_rom_block_empty_out),
    .read_grid_rdy_out(mac_k_read_grid_rdy_out),
    .read_grid_empty_out(mac_k_read_grid_empty_out),
    .read_grid_result_out(mac_k_read_grid_result_out),
    .write_grid_rdy_out(mac_k_write_grid_rdy_out),
    .write_grid_empty_out(mac_k_write_grid_empty_out),
    .set_fp32_accum_rdy_out(mac_k_set_fp32_accum_rdy_out),
    .set_fp32_accum_empty_out(mac_k_set_fp32_accum_empty_out),
    .read_fp32_accum_rdy_out(mac_k_read_fp32_accum_rdy_out),
    .read_fp32_accum_empty_out(mac_k_read_fp32_accum_empty_out),
    .read_fp32_accum_result_out(mac_k_read_fp32_accum_result_out),
    .clear_pe_rdy_out(mac_k_clear_pe_rdy_out),
    .clear_pe_empty_out(mac_k_clear_pe_empty_out),
    .clear_fp32_rdy_out(mac_k_clear_fp32_rdy_out),
    .clear_fp32_empty_out(mac_k_clear_fp32_empty_out),
    .clear_all_rdy_out(mac_k_clear_all_rdy_out),
    .clear_all_empty_out(mac_k_clear_all_empty_out),
    .stall_rate_supported_out()
  );

  mac_array u_mac_v (
    .clk(clk),
    .rst(rst),
    .mac_step_valid_in(mac_v_mac_step_valid_in),
    .mac_step_pe_id_in(mac_v_mac_step_pe_id_in),
    .mac_step_magnitude_in(mac_v_mac_step_magnitude_in),
    .mac_step_sign_bit_in(mac_v_mac_step_sign_bit_in),
    .mac_step_activation_in(mac_v_mac_step_activation_in),
    .mac_step_rden_in(mac_v_mac_step_rden_in),
    .read_accum_valid_in(mac_v_read_accum_valid_in),
    .read_accum_pe_id_in(mac_v_read_accum_pe_id_in),
    .read_accum_rden_in(mac_v_read_accum_rden_in),
    .read_rom_block_valid_in(mac_v_read_rom_block_valid_in),
    .read_rom_block_block_addr_in(mac_v_read_rom_block_block_addr_in),
    .read_rom_block_rden_in(mac_v_read_rom_block_rden_in),
    .write_rom_block_valid_in(mac_v_write_rom_block_valid_in),
    .write_rom_block_block_addr_in(mac_v_write_rom_block_block_addr_in),
    .write_rom_block_value_in(mac_v_write_rom_block_value_in),
    .write_rom_block_rden_in(mac_v_write_rom_block_rden_in),
    .read_grid_valid_in(mac_v_read_grid_valid_in),
    .read_grid_index_in(mac_v_read_grid_index_in),
    .read_grid_rden_in(mac_v_read_grid_rden_in),
    .write_grid_valid_in(mac_v_write_grid_valid_in),
    .write_grid_index_in(mac_v_write_grid_index_in),
    .write_grid_value_in(mac_v_write_grid_value_in),
    .write_grid_rden_in(mac_v_write_grid_rden_in),
    .set_fp32_accum_valid_in(mac_v_set_fp32_accum_valid_in),
    .set_fp32_accum_pe_id_in(mac_v_set_fp32_accum_pe_id_in),
    .set_fp32_accum_value_in(mac_v_set_fp32_accum_value_in),
    .set_fp32_accum_rden_in(mac_v_set_fp32_accum_rden_in),
    .read_fp32_accum_valid_in(mac_v_read_fp32_accum_valid_in),
    .read_fp32_accum_pe_id_in(mac_v_read_fp32_accum_pe_id_in),
    .read_fp32_accum_rden_in(mac_v_read_fp32_accum_rden_in),
    .clear_pe_valid_in(mac_v_clear_pe_valid_in),
    .clear_pe_pe_id_in(mac_v_clear_pe_pe_id_in),
    .clear_pe_rden_in(mac_v_clear_pe_rden_in),
    .clear_fp32_valid_in(mac_v_clear_fp32_valid_in),
    .clear_fp32_pe_id_in(mac_v_clear_fp32_pe_id_in),
    .clear_fp32_rden_in(mac_v_clear_fp32_rden_in),
    .clear_all_valid_in(mac_v_clear_all_valid_in),
    .clear_all_rden_in(mac_v_clear_all_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(mac_v_rst_and_startup_done_out),
    .mac_step_rdy_out(mac_v_mac_step_rdy_out),
    .mac_step_empty_out(mac_v_mac_step_empty_out),
    .mac_step_result_out(mac_v_mac_step_result_out),
    .read_accum_rdy_out(mac_v_read_accum_rdy_out),
    .read_accum_empty_out(mac_v_read_accum_empty_out),
    .read_accum_result_out(mac_v_read_accum_result_out),
    .read_rom_block_rdy_out(mac_v_read_rom_block_rdy_out),
    .read_rom_block_empty_out(mac_v_read_rom_block_empty_out),
    .read_rom_block_result_out(mac_v_read_rom_block_result_out),
    .write_rom_block_rdy_out(mac_v_write_rom_block_rdy_out),
    .write_rom_block_empty_out(mac_v_write_rom_block_empty_out),
    .read_grid_rdy_out(mac_v_read_grid_rdy_out),
    .read_grid_empty_out(mac_v_read_grid_empty_out),
    .read_grid_result_out(mac_v_read_grid_result_out),
    .write_grid_rdy_out(mac_v_write_grid_rdy_out),
    .write_grid_empty_out(mac_v_write_grid_empty_out),
    .set_fp32_accum_rdy_out(mac_v_set_fp32_accum_rdy_out),
    .set_fp32_accum_empty_out(mac_v_set_fp32_accum_empty_out),
    .read_fp32_accum_rdy_out(mac_v_read_fp32_accum_rdy_out),
    .read_fp32_accum_empty_out(mac_v_read_fp32_accum_empty_out),
    .read_fp32_accum_result_out(mac_v_read_fp32_accum_result_out),
    .clear_pe_rdy_out(mac_v_clear_pe_rdy_out),
    .clear_pe_empty_out(mac_v_clear_pe_empty_out),
    .clear_fp32_rdy_out(mac_v_clear_fp32_rdy_out),
    .clear_fp32_empty_out(mac_v_clear_fp32_empty_out),
    .clear_all_rdy_out(mac_v_clear_all_rdy_out),
    .clear_all_empty_out(mac_v_clear_all_empty_out),
    .stall_rate_supported_out()
  );

  mac_array u_mac_o (
    .clk(clk),
    .rst(rst),
    .mac_step_valid_in(mac_o_mac_step_valid_in),
    .mac_step_pe_id_in(mac_o_mac_step_pe_id_in),
    .mac_step_magnitude_in(mac_o_mac_step_magnitude_in),
    .mac_step_sign_bit_in(mac_o_mac_step_sign_bit_in),
    .mac_step_activation_in(mac_o_mac_step_activation_in),
    .mac_step_rden_in(mac_o_mac_step_rden_in),
    .read_accum_valid_in(mac_o_read_accum_valid_in),
    .read_accum_pe_id_in(mac_o_read_accum_pe_id_in),
    .read_accum_rden_in(mac_o_read_accum_rden_in),
    .read_rom_block_valid_in(mac_o_read_rom_block_valid_in),
    .read_rom_block_block_addr_in(mac_o_read_rom_block_block_addr_in),
    .read_rom_block_rden_in(mac_o_read_rom_block_rden_in),
    .write_rom_block_valid_in(mac_o_write_rom_block_valid_in),
    .write_rom_block_block_addr_in(mac_o_write_rom_block_block_addr_in),
    .write_rom_block_value_in(mac_o_write_rom_block_value_in),
    .write_rom_block_rden_in(mac_o_write_rom_block_rden_in),
    .read_grid_valid_in(mac_o_read_grid_valid_in),
    .read_grid_index_in(mac_o_read_grid_index_in),
    .read_grid_rden_in(mac_o_read_grid_rden_in),
    .write_grid_valid_in(mac_o_write_grid_valid_in),
    .write_grid_index_in(mac_o_write_grid_index_in),
    .write_grid_value_in(mac_o_write_grid_value_in),
    .write_grid_rden_in(mac_o_write_grid_rden_in),
    .set_fp32_accum_valid_in(mac_o_set_fp32_accum_valid_in),
    .set_fp32_accum_pe_id_in(mac_o_set_fp32_accum_pe_id_in),
    .set_fp32_accum_value_in(mac_o_set_fp32_accum_value_in),
    .set_fp32_accum_rden_in(mac_o_set_fp32_accum_rden_in),
    .read_fp32_accum_valid_in(mac_o_read_fp32_accum_valid_in),
    .read_fp32_accum_pe_id_in(mac_o_read_fp32_accum_pe_id_in),
    .read_fp32_accum_rden_in(mac_o_read_fp32_accum_rden_in),
    .clear_pe_valid_in(mac_o_clear_pe_valid_in),
    .clear_pe_pe_id_in(mac_o_clear_pe_pe_id_in),
    .clear_pe_rden_in(mac_o_clear_pe_rden_in),
    .clear_fp32_valid_in(mac_o_clear_fp32_valid_in),
    .clear_fp32_pe_id_in(mac_o_clear_fp32_pe_id_in),
    .clear_fp32_rden_in(mac_o_clear_fp32_rden_in),
    .clear_all_valid_in(mac_o_clear_all_valid_in),
    .clear_all_rden_in(mac_o_clear_all_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(mac_o_rst_and_startup_done_out),
    .mac_step_rdy_out(mac_o_mac_step_rdy_out),
    .mac_step_empty_out(mac_o_mac_step_empty_out),
    .mac_step_result_out(mac_o_mac_step_result_out),
    .read_accum_rdy_out(mac_o_read_accum_rdy_out),
    .read_accum_empty_out(mac_o_read_accum_empty_out),
    .read_accum_result_out(mac_o_read_accum_result_out),
    .read_rom_block_rdy_out(mac_o_read_rom_block_rdy_out),
    .read_rom_block_empty_out(mac_o_read_rom_block_empty_out),
    .read_rom_block_result_out(mac_o_read_rom_block_result_out),
    .write_rom_block_rdy_out(mac_o_write_rom_block_rdy_out),
    .write_rom_block_empty_out(mac_o_write_rom_block_empty_out),
    .read_grid_rdy_out(mac_o_read_grid_rdy_out),
    .read_grid_empty_out(mac_o_read_grid_empty_out),
    .read_grid_result_out(mac_o_read_grid_result_out),
    .write_grid_rdy_out(mac_o_write_grid_rdy_out),
    .write_grid_empty_out(mac_o_write_grid_empty_out),
    .set_fp32_accum_rdy_out(mac_o_set_fp32_accum_rdy_out),
    .set_fp32_accum_empty_out(mac_o_set_fp32_accum_empty_out),
    .read_fp32_accum_rdy_out(mac_o_read_fp32_accum_rdy_out),
    .read_fp32_accum_empty_out(mac_o_read_fp32_accum_empty_out),
    .read_fp32_accum_result_out(mac_o_read_fp32_accum_result_out),
    .clear_pe_rdy_out(mac_o_clear_pe_rdy_out),
    .clear_pe_empty_out(mac_o_clear_pe_empty_out),
    .clear_fp32_rdy_out(mac_o_clear_fp32_rdy_out),
    .clear_fp32_empty_out(mac_o_clear_fp32_empty_out),
    .clear_all_rdy_out(mac_o_clear_all_rdy_out),
    .clear_all_empty_out(mac_o_clear_all_empty_out),
    .stall_rate_supported_out()
  );

  mac_array u_mac_gate (
    .clk(clk),
    .rst(rst),
    .mac_step_valid_in(mac_gate_mac_step_valid_in),
    .mac_step_pe_id_in(mac_gate_mac_step_pe_id_in),
    .mac_step_magnitude_in(mac_gate_mac_step_magnitude_in),
    .mac_step_sign_bit_in(mac_gate_mac_step_sign_bit_in),
    .mac_step_activation_in(mac_gate_mac_step_activation_in),
    .mac_step_rden_in(mac_gate_mac_step_rden_in),
    .read_accum_valid_in(mac_gate_read_accum_valid_in),
    .read_accum_pe_id_in(mac_gate_read_accum_pe_id_in),
    .read_accum_rden_in(mac_gate_read_accum_rden_in),
    .read_rom_block_valid_in(mac_gate_read_rom_block_valid_in),
    .read_rom_block_block_addr_in(mac_gate_read_rom_block_block_addr_in),
    .read_rom_block_rden_in(mac_gate_read_rom_block_rden_in),
    .write_rom_block_valid_in(mac_gate_write_rom_block_valid_in),
    .write_rom_block_block_addr_in(mac_gate_write_rom_block_block_addr_in),
    .write_rom_block_value_in(mac_gate_write_rom_block_value_in),
    .write_rom_block_rden_in(mac_gate_write_rom_block_rden_in),
    .read_grid_valid_in(mac_gate_read_grid_valid_in),
    .read_grid_index_in(mac_gate_read_grid_index_in),
    .read_grid_rden_in(mac_gate_read_grid_rden_in),
    .write_grid_valid_in(mac_gate_write_grid_valid_in),
    .write_grid_index_in(mac_gate_write_grid_index_in),
    .write_grid_value_in(mac_gate_write_grid_value_in),
    .write_grid_rden_in(mac_gate_write_grid_rden_in),
    .set_fp32_accum_valid_in(mac_gate_set_fp32_accum_valid_in),
    .set_fp32_accum_pe_id_in(mac_gate_set_fp32_accum_pe_id_in),
    .set_fp32_accum_value_in(mac_gate_set_fp32_accum_value_in),
    .set_fp32_accum_rden_in(mac_gate_set_fp32_accum_rden_in),
    .read_fp32_accum_valid_in(mac_gate_read_fp32_accum_valid_in),
    .read_fp32_accum_pe_id_in(mac_gate_read_fp32_accum_pe_id_in),
    .read_fp32_accum_rden_in(mac_gate_read_fp32_accum_rden_in),
    .clear_pe_valid_in(mac_gate_clear_pe_valid_in),
    .clear_pe_pe_id_in(mac_gate_clear_pe_pe_id_in),
    .clear_pe_rden_in(mac_gate_clear_pe_rden_in),
    .clear_fp32_valid_in(mac_gate_clear_fp32_valid_in),
    .clear_fp32_pe_id_in(mac_gate_clear_fp32_pe_id_in),
    .clear_fp32_rden_in(mac_gate_clear_fp32_rden_in),
    .clear_all_valid_in(mac_gate_clear_all_valid_in),
    .clear_all_rden_in(mac_gate_clear_all_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(mac_gate_rst_and_startup_done_out),
    .mac_step_rdy_out(mac_gate_mac_step_rdy_out),
    .mac_step_empty_out(mac_gate_mac_step_empty_out),
    .mac_step_result_out(mac_gate_mac_step_result_out),
    .read_accum_rdy_out(mac_gate_read_accum_rdy_out),
    .read_accum_empty_out(mac_gate_read_accum_empty_out),
    .read_accum_result_out(mac_gate_read_accum_result_out),
    .read_rom_block_rdy_out(mac_gate_read_rom_block_rdy_out),
    .read_rom_block_empty_out(mac_gate_read_rom_block_empty_out),
    .read_rom_block_result_out(mac_gate_read_rom_block_result_out),
    .write_rom_block_rdy_out(mac_gate_write_rom_block_rdy_out),
    .write_rom_block_empty_out(mac_gate_write_rom_block_empty_out),
    .read_grid_rdy_out(mac_gate_read_grid_rdy_out),
    .read_grid_empty_out(mac_gate_read_grid_empty_out),
    .read_grid_result_out(mac_gate_read_grid_result_out),
    .write_grid_rdy_out(mac_gate_write_grid_rdy_out),
    .write_grid_empty_out(mac_gate_write_grid_empty_out),
    .set_fp32_accum_rdy_out(mac_gate_set_fp32_accum_rdy_out),
    .set_fp32_accum_empty_out(mac_gate_set_fp32_accum_empty_out),
    .read_fp32_accum_rdy_out(mac_gate_read_fp32_accum_rdy_out),
    .read_fp32_accum_empty_out(mac_gate_read_fp32_accum_empty_out),
    .read_fp32_accum_result_out(mac_gate_read_fp32_accum_result_out),
    .clear_pe_rdy_out(mac_gate_clear_pe_rdy_out),
    .clear_pe_empty_out(mac_gate_clear_pe_empty_out),
    .clear_fp32_rdy_out(mac_gate_clear_fp32_rdy_out),
    .clear_fp32_empty_out(mac_gate_clear_fp32_empty_out),
    .clear_all_rdy_out(mac_gate_clear_all_rdy_out),
    .clear_all_empty_out(mac_gate_clear_all_empty_out),
    .stall_rate_supported_out()
  );

  mac_array u_mac_up (
    .clk(clk),
    .rst(rst),
    .mac_step_valid_in(mac_up_mac_step_valid_in),
    .mac_step_pe_id_in(mac_up_mac_step_pe_id_in),
    .mac_step_magnitude_in(mac_up_mac_step_magnitude_in),
    .mac_step_sign_bit_in(mac_up_mac_step_sign_bit_in),
    .mac_step_activation_in(mac_up_mac_step_activation_in),
    .mac_step_rden_in(mac_up_mac_step_rden_in),
    .read_accum_valid_in(mac_up_read_accum_valid_in),
    .read_accum_pe_id_in(mac_up_read_accum_pe_id_in),
    .read_accum_rden_in(mac_up_read_accum_rden_in),
    .read_rom_block_valid_in(mac_up_read_rom_block_valid_in),
    .read_rom_block_block_addr_in(mac_up_read_rom_block_block_addr_in),
    .read_rom_block_rden_in(mac_up_read_rom_block_rden_in),
    .write_rom_block_valid_in(mac_up_write_rom_block_valid_in),
    .write_rom_block_block_addr_in(mac_up_write_rom_block_block_addr_in),
    .write_rom_block_value_in(mac_up_write_rom_block_value_in),
    .write_rom_block_rden_in(mac_up_write_rom_block_rden_in),
    .read_grid_valid_in(mac_up_read_grid_valid_in),
    .read_grid_index_in(mac_up_read_grid_index_in),
    .read_grid_rden_in(mac_up_read_grid_rden_in),
    .write_grid_valid_in(mac_up_write_grid_valid_in),
    .write_grid_index_in(mac_up_write_grid_index_in),
    .write_grid_value_in(mac_up_write_grid_value_in),
    .write_grid_rden_in(mac_up_write_grid_rden_in),
    .set_fp32_accum_valid_in(mac_up_set_fp32_accum_valid_in),
    .set_fp32_accum_pe_id_in(mac_up_set_fp32_accum_pe_id_in),
    .set_fp32_accum_value_in(mac_up_set_fp32_accum_value_in),
    .set_fp32_accum_rden_in(mac_up_set_fp32_accum_rden_in),
    .read_fp32_accum_valid_in(mac_up_read_fp32_accum_valid_in),
    .read_fp32_accum_pe_id_in(mac_up_read_fp32_accum_pe_id_in),
    .read_fp32_accum_rden_in(mac_up_read_fp32_accum_rden_in),
    .clear_pe_valid_in(mac_up_clear_pe_valid_in),
    .clear_pe_pe_id_in(mac_up_clear_pe_pe_id_in),
    .clear_pe_rden_in(mac_up_clear_pe_rden_in),
    .clear_fp32_valid_in(mac_up_clear_fp32_valid_in),
    .clear_fp32_pe_id_in(mac_up_clear_fp32_pe_id_in),
    .clear_fp32_rden_in(mac_up_clear_fp32_rden_in),
    .clear_all_valid_in(mac_up_clear_all_valid_in),
    .clear_all_rden_in(mac_up_clear_all_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(mac_up_rst_and_startup_done_out),
    .mac_step_rdy_out(mac_up_mac_step_rdy_out),
    .mac_step_empty_out(mac_up_mac_step_empty_out),
    .mac_step_result_out(mac_up_mac_step_result_out),
    .read_accum_rdy_out(mac_up_read_accum_rdy_out),
    .read_accum_empty_out(mac_up_read_accum_empty_out),
    .read_accum_result_out(mac_up_read_accum_result_out),
    .read_rom_block_rdy_out(mac_up_read_rom_block_rdy_out),
    .read_rom_block_empty_out(mac_up_read_rom_block_empty_out),
    .read_rom_block_result_out(mac_up_read_rom_block_result_out),
    .write_rom_block_rdy_out(mac_up_write_rom_block_rdy_out),
    .write_rom_block_empty_out(mac_up_write_rom_block_empty_out),
    .read_grid_rdy_out(mac_up_read_grid_rdy_out),
    .read_grid_empty_out(mac_up_read_grid_empty_out),
    .read_grid_result_out(mac_up_read_grid_result_out),
    .write_grid_rdy_out(mac_up_write_grid_rdy_out),
    .write_grid_empty_out(mac_up_write_grid_empty_out),
    .set_fp32_accum_rdy_out(mac_up_set_fp32_accum_rdy_out),
    .set_fp32_accum_empty_out(mac_up_set_fp32_accum_empty_out),
    .read_fp32_accum_rdy_out(mac_up_read_fp32_accum_rdy_out),
    .read_fp32_accum_empty_out(mac_up_read_fp32_accum_empty_out),
    .read_fp32_accum_result_out(mac_up_read_fp32_accum_result_out),
    .clear_pe_rdy_out(mac_up_clear_pe_rdy_out),
    .clear_pe_empty_out(mac_up_clear_pe_empty_out),
    .clear_fp32_rdy_out(mac_up_clear_fp32_rdy_out),
    .clear_fp32_empty_out(mac_up_clear_fp32_empty_out),
    .clear_all_rdy_out(mac_up_clear_all_rdy_out),
    .clear_all_empty_out(mac_up_clear_all_empty_out),
    .stall_rate_supported_out()
  );

  mac_array u_mac_down (
    .clk(clk),
    .rst(rst),
    .mac_step_valid_in(mac_down_mac_step_valid_in),
    .mac_step_pe_id_in(mac_down_mac_step_pe_id_in),
    .mac_step_magnitude_in(mac_down_mac_step_magnitude_in),
    .mac_step_sign_bit_in(mac_down_mac_step_sign_bit_in),
    .mac_step_activation_in(mac_down_mac_step_activation_in),
    .mac_step_rden_in(mac_down_mac_step_rden_in),
    .read_accum_valid_in(mac_down_read_accum_valid_in),
    .read_accum_pe_id_in(mac_down_read_accum_pe_id_in),
    .read_accum_rden_in(mac_down_read_accum_rden_in),
    .read_rom_block_valid_in(mac_down_read_rom_block_valid_in),
    .read_rom_block_block_addr_in(mac_down_read_rom_block_block_addr_in),
    .read_rom_block_rden_in(mac_down_read_rom_block_rden_in),
    .write_rom_block_valid_in(mac_down_write_rom_block_valid_in),
    .write_rom_block_block_addr_in(mac_down_write_rom_block_block_addr_in),
    .write_rom_block_value_in(mac_down_write_rom_block_value_in),
    .write_rom_block_rden_in(mac_down_write_rom_block_rden_in),
    .read_grid_valid_in(mac_down_read_grid_valid_in),
    .read_grid_index_in(mac_down_read_grid_index_in),
    .read_grid_rden_in(mac_down_read_grid_rden_in),
    .write_grid_valid_in(mac_down_write_grid_valid_in),
    .write_grid_index_in(mac_down_write_grid_index_in),
    .write_grid_value_in(mac_down_write_grid_value_in),
    .write_grid_rden_in(mac_down_write_grid_rden_in),
    .set_fp32_accum_valid_in(mac_down_set_fp32_accum_valid_in),
    .set_fp32_accum_pe_id_in(mac_down_set_fp32_accum_pe_id_in),
    .set_fp32_accum_value_in(mac_down_set_fp32_accum_value_in),
    .set_fp32_accum_rden_in(mac_down_set_fp32_accum_rden_in),
    .read_fp32_accum_valid_in(mac_down_read_fp32_accum_valid_in),
    .read_fp32_accum_pe_id_in(mac_down_read_fp32_accum_pe_id_in),
    .read_fp32_accum_rden_in(mac_down_read_fp32_accum_rden_in),
    .clear_pe_valid_in(mac_down_clear_pe_valid_in),
    .clear_pe_pe_id_in(mac_down_clear_pe_pe_id_in),
    .clear_pe_rden_in(mac_down_clear_pe_rden_in),
    .clear_fp32_valid_in(mac_down_clear_fp32_valid_in),
    .clear_fp32_pe_id_in(mac_down_clear_fp32_pe_id_in),
    .clear_fp32_rden_in(mac_down_clear_fp32_rden_in),
    .clear_all_valid_in(mac_down_clear_all_valid_in),
    .clear_all_rden_in(mac_down_clear_all_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(mac_down_rst_and_startup_done_out),
    .mac_step_rdy_out(mac_down_mac_step_rdy_out),
    .mac_step_empty_out(mac_down_mac_step_empty_out),
    .mac_step_result_out(mac_down_mac_step_result_out),
    .read_accum_rdy_out(mac_down_read_accum_rdy_out),
    .read_accum_empty_out(mac_down_read_accum_empty_out),
    .read_accum_result_out(mac_down_read_accum_result_out),
    .read_rom_block_rdy_out(mac_down_read_rom_block_rdy_out),
    .read_rom_block_empty_out(mac_down_read_rom_block_empty_out),
    .read_rom_block_result_out(mac_down_read_rom_block_result_out),
    .write_rom_block_rdy_out(mac_down_write_rom_block_rdy_out),
    .write_rom_block_empty_out(mac_down_write_rom_block_empty_out),
    .read_grid_rdy_out(mac_down_read_grid_rdy_out),
    .read_grid_empty_out(mac_down_read_grid_empty_out),
    .read_grid_result_out(mac_down_read_grid_result_out),
    .write_grid_rdy_out(mac_down_write_grid_rdy_out),
    .write_grid_empty_out(mac_down_write_grid_empty_out),
    .set_fp32_accum_rdy_out(mac_down_set_fp32_accum_rdy_out),
    .set_fp32_accum_empty_out(mac_down_set_fp32_accum_empty_out),
    .read_fp32_accum_rdy_out(mac_down_read_fp32_accum_rdy_out),
    .read_fp32_accum_empty_out(mac_down_read_fp32_accum_empty_out),
    .read_fp32_accum_result_out(mac_down_read_fp32_accum_result_out),
    .clear_pe_rdy_out(mac_down_clear_pe_rdy_out),
    .clear_pe_empty_out(mac_down_clear_pe_empty_out),
    .clear_fp32_rdy_out(mac_down_clear_fp32_rdy_out),
    .clear_fp32_empty_out(mac_down_clear_fp32_empty_out),
    .clear_all_rdy_out(mac_down_clear_all_rdy_out),
    .clear_all_empty_out(mac_down_clear_all_empty_out),
    .stall_rate_supported_out()
  );

  vector_unit u_vpu (
    .clk(clk),
    .rst(rst),
    .rmsnorm_accumulate_valid_in(vpu_rmsnorm_accumulate_valid_in),
    .rmsnorm_accumulate_x_bf16_in(vpu_rmsnorm_accumulate_x_bf16_in),
    .rmsnorm_accumulate_rden_in(vpu_rmsnorm_accumulate_rden_in),
    .rmsnorm_get_sum_valid_in(vpu_rmsnorm_get_sum_valid_in),
    .rmsnorm_get_sum_rden_in(vpu_rmsnorm_get_sum_rden_in),
    .rmsnorm_reset_valid_in(vpu_rmsnorm_reset_valid_in),
    .rmsnorm_reset_rden_in(vpu_rmsnorm_reset_rden_in),
    .set_gamma_pre_attn_valid_in(vpu_set_gamma_pre_attn_valid_in),
    .set_gamma_pre_attn_index_in(vpu_set_gamma_pre_attn_index_in),
    .set_gamma_pre_attn_value_in(vpu_set_gamma_pre_attn_value_in),
    .set_gamma_pre_attn_rden_in(vpu_set_gamma_pre_attn_rden_in),
    .get_gamma_pre_attn_valid_in(vpu_get_gamma_pre_attn_valid_in),
    .get_gamma_pre_attn_index_in(vpu_get_gamma_pre_attn_index_in),
    .get_gamma_pre_attn_rden_in(vpu_get_gamma_pre_attn_rden_in),
    .set_gamma_pre_mlp_valid_in(vpu_set_gamma_pre_mlp_valid_in),
    .set_gamma_pre_mlp_index_in(vpu_set_gamma_pre_mlp_index_in),
    .set_gamma_pre_mlp_value_in(vpu_set_gamma_pre_mlp_value_in),
    .set_gamma_pre_mlp_rden_in(vpu_set_gamma_pre_mlp_rden_in),
    .get_gamma_pre_mlp_valid_in(vpu_get_gamma_pre_mlp_valid_in),
    .get_gamma_pre_mlp_index_in(vpu_get_gamma_pre_mlp_index_in),
    .get_gamma_pre_mlp_rden_in(vpu_get_gamma_pre_mlp_rden_in),
    .set_rsqrt_lut_valid_in(vpu_set_rsqrt_lut_valid_in),
    .set_rsqrt_lut_index_in(vpu_set_rsqrt_lut_index_in),
    .set_rsqrt_lut_value_in(vpu_set_rsqrt_lut_value_in),
    .set_rsqrt_lut_rden_in(vpu_set_rsqrt_lut_rden_in),
    .lookup_rsqrt_valid_in(vpu_lookup_rsqrt_valid_in),
    .lookup_rsqrt_index_in(vpu_lookup_rsqrt_index_in),
    .lookup_rsqrt_rden_in(vpu_lookup_rsqrt_rden_in),
    .rope_read_cos_row_valid_in(vpu_rope_read_cos_row_valid_in),
    .rope_read_cos_row_position_in(vpu_rope_read_cos_row_position_in),
    .rope_read_cos_row_rden_in(vpu_rope_read_cos_row_rden_in),
    .rope_read_sin_row_valid_in(vpu_rope_read_sin_row_valid_in),
    .rope_read_sin_row_position_in(vpu_rope_read_sin_row_position_in),
    .rope_read_sin_row_rden_in(vpu_rope_read_sin_row_rden_in),
    .rope_write_cos_row_valid_in(vpu_rope_write_cos_row_valid_in),
    .rope_write_cos_row_position_in(vpu_rope_write_cos_row_position_in),
    .rope_write_cos_row_value_in(vpu_rope_write_cos_row_value_in),
    .rope_write_cos_row_rden_in(vpu_rope_write_cos_row_rden_in),
    .rope_write_sin_row_valid_in(vpu_rope_write_sin_row_valid_in),
    .rope_write_sin_row_position_in(vpu_rope_write_sin_row_position_in),
    .rope_write_sin_row_value_in(vpu_rope_write_sin_row_value_in),
    .rope_write_sin_row_rden_in(vpu_rope_write_sin_row_rden_in),
    .set_sigmoid_lut_valid_in(vpu_set_sigmoid_lut_valid_in),
    .set_sigmoid_lut_index_in(vpu_set_sigmoid_lut_index_in),
    .set_sigmoid_lut_value_in(vpu_set_sigmoid_lut_value_in),
    .set_sigmoid_lut_rden_in(vpu_set_sigmoid_lut_rden_in),
    .swiglu_compute_valid_in(vpu_swiglu_compute_valid_in),
    .swiglu_compute_gate_bf16_in(vpu_swiglu_compute_gate_bf16_in),
    .swiglu_compute_up_bf16_in(vpu_swiglu_compute_up_bf16_in),
    .swiglu_compute_rden_in(vpu_swiglu_compute_rden_in),
    .dequantize_valid_in(vpu_dequantize_valid_in),
    .dequantize_accum_in(vpu_dequantize_accum_in),
    .dequantize_super_scale_bf16_in(vpu_dequantize_super_scale_bf16_in),
    .dequantize_sub_scale_in(vpu_dequantize_sub_scale_in),
    .dequantize_rden_in(vpu_dequantize_rden_in),
    .residual_add_valid_in(vpu_residual_add_valid_in),
    .residual_add_a_bf16_in(vpu_residual_add_a_bf16_in),
    .residual_add_b_bf16_in(vpu_residual_add_b_bf16_in),
    .residual_add_rden_in(vpu_residual_add_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(vpu_rst_and_startup_done_out),
    .rmsnorm_accumulate_rdy_out(vpu_rmsnorm_accumulate_rdy_out),
    .rmsnorm_accumulate_empty_out(vpu_rmsnorm_accumulate_empty_out),
    .rmsnorm_get_sum_rdy_out(vpu_rmsnorm_get_sum_rdy_out),
    .rmsnorm_get_sum_empty_out(vpu_rmsnorm_get_sum_empty_out),
    .rmsnorm_get_sum_result_out(vpu_rmsnorm_get_sum_result_out),
    .rmsnorm_reset_rdy_out(vpu_rmsnorm_reset_rdy_out),
    .rmsnorm_reset_empty_out(vpu_rmsnorm_reset_empty_out),
    .set_gamma_pre_attn_rdy_out(vpu_set_gamma_pre_attn_rdy_out),
    .set_gamma_pre_attn_empty_out(vpu_set_gamma_pre_attn_empty_out),
    .get_gamma_pre_attn_rdy_out(vpu_get_gamma_pre_attn_rdy_out),
    .get_gamma_pre_attn_empty_out(vpu_get_gamma_pre_attn_empty_out),
    .get_gamma_pre_attn_result_out(vpu_get_gamma_pre_attn_result_out),
    .set_gamma_pre_mlp_rdy_out(vpu_set_gamma_pre_mlp_rdy_out),
    .set_gamma_pre_mlp_empty_out(vpu_set_gamma_pre_mlp_empty_out),
    .get_gamma_pre_mlp_rdy_out(vpu_get_gamma_pre_mlp_rdy_out),
    .get_gamma_pre_mlp_empty_out(vpu_get_gamma_pre_mlp_empty_out),
    .get_gamma_pre_mlp_result_out(vpu_get_gamma_pre_mlp_result_out),
    .set_rsqrt_lut_rdy_out(vpu_set_rsqrt_lut_rdy_out),
    .set_rsqrt_lut_empty_out(vpu_set_rsqrt_lut_empty_out),
    .lookup_rsqrt_rdy_out(vpu_lookup_rsqrt_rdy_out),
    .lookup_rsqrt_empty_out(vpu_lookup_rsqrt_empty_out),
    .lookup_rsqrt_result_out(vpu_lookup_rsqrt_result_out),
    .rope_read_cos_row_rdy_out(vpu_rope_read_cos_row_rdy_out),
    .rope_read_cos_row_empty_out(vpu_rope_read_cos_row_empty_out),
    .rope_read_cos_row_result_out(vpu_rope_read_cos_row_result_out),
    .rope_read_sin_row_rdy_out(vpu_rope_read_sin_row_rdy_out),
    .rope_read_sin_row_empty_out(vpu_rope_read_sin_row_empty_out),
    .rope_read_sin_row_result_out(vpu_rope_read_sin_row_result_out),
    .rope_write_cos_row_rdy_out(vpu_rope_write_cos_row_rdy_out),
    .rope_write_cos_row_empty_out(vpu_rope_write_cos_row_empty_out),
    .rope_write_sin_row_rdy_out(vpu_rope_write_sin_row_rdy_out),
    .rope_write_sin_row_empty_out(vpu_rope_write_sin_row_empty_out),
    .set_sigmoid_lut_rdy_out(vpu_set_sigmoid_lut_rdy_out),
    .set_sigmoid_lut_empty_out(vpu_set_sigmoid_lut_empty_out),
    .swiglu_compute_rdy_out(vpu_swiglu_compute_rdy_out),
    .swiglu_compute_empty_out(vpu_swiglu_compute_empty_out),
    .swiglu_compute_result_out(vpu_swiglu_compute_result_out),
    .dequantize_rdy_out(vpu_dequantize_rdy_out),
    .dequantize_empty_out(vpu_dequantize_empty_out),
    .dequantize_result_out(vpu_dequantize_result_out),
    .residual_add_rdy_out(vpu_residual_add_rdy_out),
    .residual_add_empty_out(vpu_residual_add_empty_out),
    .residual_add_result_out(vpu_residual_add_result_out),
    .stall_rate_supported_out()
  );

  kv_cache u_kvc (
    .clk(clk),
    .rst(rst),
    .append_k_valid_in(kvc_append_k_valid_in),
    .append_k_token_pos_in(kvc_append_k_token_pos_in),
    .append_k_head_id_in(kvc_append_k_head_id_in),
    .append_k_dim_idx_in(kvc_append_k_dim_idx_in),
    .append_k_value_in(kvc_append_k_value_in),
    .append_k_rden_in(kvc_append_k_rden_in),
    .append_v_valid_in(kvc_append_v_valid_in),
    .append_v_token_pos_in(kvc_append_v_token_pos_in),
    .append_v_head_id_in(kvc_append_v_head_id_in),
    .append_v_dim_idx_in(kvc_append_v_dim_idx_in),
    .append_v_value_in(kvc_append_v_value_in),
    .append_v_rden_in(kvc_append_v_rden_in),
    .read_k_valid_in(kvc_read_k_valid_in),
    .read_k_token_pos_in(kvc_read_k_token_pos_in),
    .read_k_head_id_in(kvc_read_k_head_id_in),
    .read_k_dim_idx_in(kvc_read_k_dim_idx_in),
    .read_k_rden_in(kvc_read_k_rden_in),
    .read_v_valid_in(kvc_read_v_valid_in),
    .read_v_token_pos_in(kvc_read_v_token_pos_in),
    .read_v_head_id_in(kvc_read_v_head_id_in),
    .read_v_dim_idx_in(kvc_read_v_dim_idx_in),
    .read_v_rden_in(kvc_read_v_rden_in),
    .advance_write_ptr_valid_in(kvc_advance_write_ptr_valid_in),
    .advance_write_ptr_rden_in(kvc_advance_write_ptr_rden_in),
    .get_seq_len_valid_in(kvc_get_seq_len_valid_in),
    .get_seq_len_rden_in(kvc_get_seq_len_rden_in),
    .reset_valid_in(kvc_reset_valid_in),
    .reset_rden_in(kvc_reset_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(kvc_rst_and_startup_done_out),
    .append_k_rdy_out(kvc_append_k_rdy_out),
    .append_k_empty_out(kvc_append_k_empty_out),
    .append_v_rdy_out(kvc_append_v_rdy_out),
    .append_v_empty_out(kvc_append_v_empty_out),
    .read_k_rdy_out(kvc_read_k_rdy_out),
    .read_k_empty_out(kvc_read_k_empty_out),
    .read_k_result_out(kvc_read_k_result_out),
    .read_v_rdy_out(kvc_read_v_rdy_out),
    .read_v_empty_out(kvc_read_v_empty_out),
    .read_v_result_out(kvc_read_v_result_out),
    .advance_write_ptr_rdy_out(kvc_advance_write_ptr_rdy_out),
    .advance_write_ptr_empty_out(kvc_advance_write_ptr_empty_out),
    .get_seq_len_rdy_out(kvc_get_seq_len_rdy_out),
    .get_seq_len_empty_out(kvc_get_seq_len_empty_out),
    .get_seq_len_result_out(kvc_get_seq_len_result_out),
    .reset_rdy_out(kvc_reset_rdy_out),
    .reset_empty_out(kvc_reset_empty_out),
    .stall_rate_supported_out()
  );

  attention_unit u_attn (
    .clk(clk),
    .rst(rst),
    .dot_product_valid_in(attn_dot_product_valid_in),
    .dot_product_q_elem_in(attn_dot_product_q_elem_in),
    .dot_product_k_elem_in(attn_dot_product_k_elem_in),
    .dot_product_rden_in(attn_dot_product_rden_in),
    .read_score_valid_in(attn_read_score_valid_in),
    .read_score_rden_in(attn_read_score_rden_in),
    .clear_score_valid_in(attn_clear_score_valid_in),
    .clear_score_rden_in(attn_clear_score_rden_in),
    .set_max_score_valid_in(attn_set_max_score_valid_in),
    .set_max_score_score_in(attn_set_max_score_score_in),
    .set_max_score_rden_in(attn_set_max_score_rden_in),
    .get_max_score_valid_in(attn_get_max_score_valid_in),
    .get_max_score_rden_in(attn_get_max_score_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(attn_rst_and_startup_done_out),
    .dot_product_rdy_out(attn_dot_product_rdy_out),
    .dot_product_empty_out(attn_dot_product_empty_out),
    .dot_product_result_out(attn_dot_product_result_out),
    .read_score_rdy_out(attn_read_score_rdy_out),
    .read_score_empty_out(attn_read_score_empty_out),
    .read_score_result_out(attn_read_score_result_out),
    .clear_score_rdy_out(attn_clear_score_rdy_out),
    .clear_score_empty_out(attn_clear_score_empty_out),
    .set_max_score_rdy_out(attn_set_max_score_rdy_out),
    .set_max_score_empty_out(attn_set_max_score_empty_out),
    .get_max_score_rdy_out(attn_get_max_score_rdy_out),
    .get_max_score_empty_out(attn_get_max_score_empty_out),
    .get_max_score_result_out(attn_get_max_score_result_out),
    .stall_rate_supported_out()
  );

  layer_tile u_fsm (
    .clk(clk),
    .rst(rst),
    .set_layer_id_valid_in(fsm_set_layer_id_valid_in),
    .set_layer_id_id_in(fsm_set_layer_id_id_in),
    .set_layer_id_rden_in(fsm_set_layer_id_rden_in),
    .get_layer_id_valid_in(fsm_get_layer_id_valid_in),
    .get_layer_id_rden_in(fsm_get_layer_id_rden_in),
    .get_state_valid_in(fsm_get_state_valid_in),
    .get_state_rden_in(fsm_get_state_rden_in),
    .advance_state_valid_in(fsm_advance_state_valid_in),
    .advance_state_rden_in(fsm_advance_state_rden_in),
    .reset_state_valid_in(fsm_reset_state_valid_in),
    .reset_state_rden_in(fsm_reset_state_rden_in),
    .is_done_valid_in(fsm_is_done_valid_in),
    .is_done_rden_in(fsm_is_done_rden_in),
    .get_position_valid_in(fsm_get_position_valid_in),
    .get_position_rden_in(fsm_get_position_rden_in),
    .advance_position_valid_in(fsm_advance_position_valid_in),
    .advance_position_rden_in(fsm_advance_position_rden_in),
    .reset_valid_in(fsm_reset_valid_in),
    .reset_rden_in(fsm_reset_rden_in),
    .stall_rate_in(stall_rate_in),
    .stall_rate_valid_in(stall_rate_valid_in),
    .rst_and_startup_done_out(fsm_rst_and_startup_done_out),
    .set_layer_id_rdy_out(fsm_set_layer_id_rdy_out),
    .set_layer_id_empty_out(fsm_set_layer_id_empty_out),
    .get_layer_id_rdy_out(fsm_get_layer_id_rdy_out),
    .get_layer_id_empty_out(fsm_get_layer_id_empty_out),
    .get_layer_id_result_out(fsm_get_layer_id_result_out),
    .get_state_rdy_out(fsm_get_state_rdy_out),
    .get_state_empty_out(fsm_get_state_empty_out),
    .get_state_result_out(fsm_get_state_result_out),
    .advance_state_rdy_out(fsm_advance_state_rdy_out),
    .advance_state_empty_out(fsm_advance_state_empty_out),
    .reset_state_rdy_out(fsm_reset_state_rdy_out),
    .reset_state_empty_out(fsm_reset_state_empty_out),
    .is_done_rdy_out(fsm_is_done_rdy_out),
    .is_done_empty_out(fsm_is_done_empty_out),
    .is_done_result_out(fsm_is_done_result_out),
    .get_position_rdy_out(fsm_get_position_rdy_out),
    .get_position_empty_out(fsm_get_position_empty_out),
    .get_position_result_out(fsm_get_position_result_out),
    .advance_position_rdy_out(fsm_advance_position_rdy_out),
    .advance_position_empty_out(fsm_advance_position_empty_out),
    .reset_rdy_out(fsm_reset_rdy_out),
    .reset_empty_out(fsm_reset_empty_out),
    .stall_rate_supported_out()
  );

endmodule
