#!/usr/bin/env python3
"""Generate rtl/sv/transformer_layer_block.sv from transformer_layer_wrapper.sv.

The layer block is a thin wrapper that exposes only the chip-level cascade ports
(ra_*) + clk/rst/stall_rate. All other layer ports (mac_*, vpu_*, kvc_*, attn_*,
fsm_*) are tied off internally — the chip-level testbench drives them indirectly
through the layer's internal FSM (passive in this revision; future work routes
chip-level llama_chip control here).

Re-run this script whenever transformer_layer_wrapper.sv port list changes.
"""

import re

WRAPPER = '/home/mana/workspace/OpenTaalas/rtl/sv/transformer_layer_wrapper.sv'
OUTPUT  = '/home/mana/workspace/OpenTaalas/rtl/sv/transformer_layer_block.sv'

EXPOSE_PATTERNS = ['clk', 'rst', 'stall_rate_in', 'stall_rate_valid_in']
EXPOSE_PREFIXES = ['ra_']

with open(WRAPPER) as f:
    src = f.read()

m = re.search(r'module\s+transformer_layer_wrapper\s*\(\s*(.*?)\s*\);', src, re.DOTALL)
assert m, "could not find transformer_layer_wrapper module declaration"
ports_block = m.group(1)

port_re = re.compile(r'(input|output)\s+wire\s*(\[\s*(\d+)\s*:\s*0\s*\])?\s*([a-zA-Z_][\w]*)\s*[,)]?')
ports = []
for line in ports_block.split('\n'):
    line = line.strip()
    if not line or line.startswith('//'):
        continue
    pm = port_re.search(line)
    if pm:
        direction = pm.group(1)
        width = int(pm.group(3)) + 1 if pm.group(3) else 1
        name = pm.group(4)
        ports.append((direction, width, name))


def is_exposed(name):
    return name in EXPOSE_PATTERNS or any(name.startswith(p) for p in EXPOSE_PREFIXES)


exposed = [p for p in ports if is_exposed(p[2])]
hidden  = [p for p in ports if not is_exposed(p[2])]


def fmt_width(w):
    return f"[{w-1}:0] " if w > 1 else "        "


lines = []
lines.append("// AUTO-GENERATED by scripts/gen_layer_block_min.py — DO NOT EDIT.")
lines.append("// Wraps transformer_layer_wrapper, exposing only chip-level cascade + clk/rst/stall_rate.")
lines.append("// All non-cascade layer ports are tied off internally.")
lines.append(f"// transformer_layer_wrapper ports: {len(ports)} (exposed: {len(exposed)}, tied off: {len(hidden)})")
lines.append("")
lines.append("module transformer_layer_block (")
last = len(exposed) - 1
for i, (d, w, n) in enumerate(exposed):
    comma = ',' if i < last else ''
    lines.append(f"  {d:6s} wire {fmt_width(w)}{n}{comma}")
lines.append(");")
lines.append("")
lines.append("  transformer_layer_wrapper u_layer (")
all_ports = exposed + hidden
exposed_names = {p[2] for p in exposed}
for i, (d, w, n) in enumerate(all_ports):
    is_last = (i == len(all_ports) - 1)
    comma = '' if is_last else ','
    if n in exposed_names:
        lines.append(f"    .{n}({n}){comma}")
    else:
        if d == 'input':
            lines.append(f"    .{n}({w}'b0){comma}")
        else:
            lines.append(f"    .{n}(){comma}")
lines.append("  );")
lines.append("")
lines.append("endmodule")

with open(OUTPUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"Wrote {OUTPUT}: {len(exposed)} exposed ports, {len(hidden)} tied off.")
