#pragma once
// tools/rom_sv_generator.h — Blackbox ROM SV generator for co-simulation
//
// Generates SystemVerilog files containing KanagawaHALDualPortRAM modules
// with memory pre-initialized via `initial begin` blocks.  The generated
// module is a drop-in replacement for the mock HAL RAM used by
// Kanagawa-generated RTL.
//
// Usage:
//   std::vector<uint64_t> data = { 0xAB, 0, 0xCD, ... };
//   opentaalas::generate_rom_sv("rom.sv", "weight ROM", 8, 256, data);

#include <cstdint>
#include <cstdio>
#include <stdexcept>
#include <string>
#include <vector>

namespace opentaalas {

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
namespace detail {

// Ceiling of log2, matching SystemVerilog $clog2 semantics.
// Returns at least 1 (need at least 1 address bit).
inline int clog2(int n) {
    if (n <= 1) return 1;
    int bits = 0;
    int v = n - 1;
    while (v > 0) {
        bits++;
        v >>= 1;
    }
    return bits;
}

} // namespace detail

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Generate a SV file with a KanagawaHALDualPortRAM module whose memory
/// is pre-initialized from the given data.
///
/// @param output_path  Path to write the .sv file
/// @param comment      Descriptive comment for the file header
/// @param data_width   Bit width of each memory entry (e.g. 3, 8, 16, 32)
/// @param depth        Total number of entries
/// @param init_data    Initial values (one per address, size <= depth).
///                     Addresses beyond init_data.size() default to 0.
///                     Only non-zero entries are emitted (sparse optimization).
inline void generate_rom_sv(
    const std::string& output_path,
    const std::string& comment,
    int data_width,
    int depth,
    const std::vector<uint64_t>& init_data)
{
    FILE* f = std::fopen(output_path.c_str(), "w");
    if (!f) {
        throw std::runtime_error("rom_sv_generator: cannot open " + output_path);
    }

    int addr_width = detail::clog2(depth);
    int hex_digits = (data_width + 3) / 4;

    // --- File header ---
    std::fprintf(f, "// Auto-generated blackbox ROM: %s\n", comment.c_str());
    std::fprintf(f, "// Generated by OpenTaalas rom_sv_generator\n\n");
    std::fprintf(f, "`ifndef SIMULATION\n");
    std::fprintf(f, "    `error \"This file is only supported in simulation\"\n");
    std::fprintf(f, "`endif\n\n");

    // --- Module declaration ---
    std::fprintf(f, "/* verilator lint_off DECLFILENAME */\n");
    std::fprintf(f, "module KanagawaHALDualPortRAM\n");
    std::fprintf(f, "#(\n");
    std::fprintf(f, "    parameter DATA_WIDTH = %d,\n", data_width);
    std::fprintf(f, "    parameter ADDR_WIDTH = %d,\n", addr_width);
    std::fprintf(f, "    parameter DEPTH = %d,\n", depth);
    std::fprintf(f, "    parameter USE_OUTPUT_REG = 0,\n");
    std::fprintf(f, "    parameter INITIAL_DATA_FILE = \"UNUSED\",\n");
    std::fprintf(f, "    parameter TRUE_DUAL_PORT = 0,\n");
    std::fprintf(f, "    parameter USE_HARDENED_BYPASS = 0,\n");
    std::fprintf(f, "/* verilator lint_off UNUSEDPARAM */\n");
    std::fprintf(f, "    parameter MAX_DEPTH = 0,\n");
    std::fprintf(f, "    parameter DEVICE_FAMILY = \"mock\",\n");
    std::fprintf(f, "    parameter USE_LUTRAM = 0,\n");
    std::fprintf(f, "    parameter USE_BRAM = 0,\n");
    std::fprintf(f, "    parameter SUPPORTS_RW_COLLISIONS = 0,\n");
    std::fprintf(f, "    parameter RW_COLLISIONS_IMPOSSIBLE = 0,\n");
    std::fprintf(f, "    parameter ECC\n");
    std::fprintf(f, "/* verilator lint_on UNUSEDPARAM */\n");
    std::fprintf(f, ")\n");
    std::fprintf(f, "(\n");
    std::fprintf(f, "    input wire clk,\n");
    std::fprintf(f, "    input wire [1:0][ADDR_WIDTH-1:0] addr_in,\n");
    std::fprintf(f, "    input wire [1:0] wren_in,\n");
    std::fprintf(f, "    input wire [1:0][DATA_WIDTH-1:0] data_in,\n");
    std::fprintf(f, "    input wire inject_correctable_error_in,\n");
    std::fprintf(f, "    input wire inject_uncorrectable_error_in,\n");
    std::fprintf(f, "    input wire [1:0] rden_in,\n");
    std::fprintf(f, "    output logic [1:0][DATA_WIDTH-1:0] data_out,\n");
    std::fprintf(f, "    output logic error_detected_out,\n");
    std::fprintf(f, "    output logic data_valid_out\n");
    std::fprintf(f, ");\n\n");

    // --- Internal types and storage ---
    std::fprintf(f, "    typedef logic [DATA_WIDTH-1:0] data_t;\n");
    std::fprintf(f, "    typedef logic [ADDR_WIDTH-1:0] addr_t;\n\n");
    std::fprintf(f, "    data_t mem [0:DEPTH-1];\n\n");
    std::fprintf(f, "    logic [1:0][DATA_WIDTH-1:0] internal_rddata;\n\n");

    // --- Initial block (sparse: only non-zero entries) ---
    std::fprintf(f, "    initial begin\n");
    std::fprintf(f, "        for (int i = 0; i < DEPTH; i++) mem[i] = '0;\n");

    int n = static_cast<int>(init_data.size());
    if (n > depth) n = depth;

    bool has_nonzero = false;
    for (int i = 0; i < n; i++) {
        if (init_data[i] != 0) {
            has_nonzero = true;
            break;
        }
    }
    if (has_nonzero) {
        std::fprintf(f, "        // Non-zero entries only (sparse)\n");
        for (int i = 0; i < n; i++) {
            if (init_data[i] != 0) {
                std::fprintf(f, "        mem[%d] = %d'h%0*llX;\n",
                             i, data_width, hex_digits,
                             static_cast<unsigned long long>(init_data[i]));
            }
        }
    }

    std::fprintf(f, "    end\n\n");

    // --- Write logic ---
    std::fprintf(f, "    // Writes\n");
    std::fprintf(f, "    always @(posedge clk) begin\n");
    std::fprintf(f, "        if (wren_in[0]) begin\n");
    std::fprintf(f, "            mem[addr_in[0]] <= data_in[0];\n");
    std::fprintf(f, "        end\n");
    std::fprintf(f, "        else if ((TRUE_DUAL_PORT != 0) && wren_in[1]) begin\n");
    std::fprintf(f, "            mem[addr_in[1]] <= data_in[1];\n");
    std::fprintf(f, "        end\n");
    std::fprintf(f, "    end\n\n");

    // --- Read logic ---
    std::fprintf(f, "    // Reads\n");
    std::fprintf(f, "    always_ff @(posedge clk) begin\n");
    std::fprintf(f, "        if (rden_in[1]) begin\n");
    std::fprintf(f, "            internal_rddata[1] <= mem[addr_in[1]];\n");
    std::fprintf(f, "        end\n");
    std::fprintf(f, "        if ((TRUE_DUAL_PORT != 0) && rden_in[0]) begin\n");
    std::fprintf(f, "            internal_rddata[0] <= mem[addr_in[0]];\n");
    std::fprintf(f, "        end\n");
    std::fprintf(f, "    end\n\n");

    // --- Output register generate block ---
    std::fprintf(f, "    generate\n");
    std::fprintf(f, "        if (USE_OUTPUT_REG) begin : gen_use_output_reg\n");
    std::fprintf(f, "            always_ff @(posedge clk) begin\n");
    std::fprintf(f, "                data_out <= internal_rddata;\n");
    std::fprintf(f, "                error_detected_out <= 1'b0;\n");
    std::fprintf(f, "                data_valid_out <= 1'b1;\n");
    std::fprintf(f, "            end\n");
    std::fprintf(f, "        end\n");
    std::fprintf(f, "        else begin : gen_no_output_reg\n");
    std::fprintf(f, "            always_comb begin\n");
    std::fprintf(f, "                data_out = internal_rddata;\n");
    std::fprintf(f, "                error_detected_out = 1'b0;\n");
    std::fprintf(f, "                data_valid_out = 1'b1;\n");
    std::fprintf(f, "            end\n");
    std::fprintf(f, "        end\n");
    std::fprintf(f, "    endgenerate\n\n");

    std::fprintf(f, "endmodule\n");
    std::fprintf(f, "/* verilator lint_on DECLFILENAME */\n");

    std::fclose(f);
}

} // namespace opentaalas
